### ISSUE TITLE
Can't install pupil-labs/pyndsi package

### ISSUE THREAD

**Issue by kemics** [pupil-labs/pupil#1132] opened 2018-03-26 21:31 UTC
Hello,

I was trying to launch the app, but I got an error while adding https://github.com/pupil-labs/pyndsi dependency. This repository has an issue about the same error https://github.com/pupil-labs/pyndsi/issues/35  but the guide from ticket did not work for me.

The error message:
```
<scratch space>:55:1: note: expanded from here
    "ndsi/h264/mp4_writer.cpp"
    ^
    ndsi/h264/mp4_writer.cpp:157:3: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
                    LOGE("could not start because no MediaStream were added");
                    ^
    ndsi/h264/utilbase.h:94:89: note: expanded from macro 'LOGE'
                    #define LOGE(FMT, ...) fprintf(stderr, "[E/" LOG_TAG ":%s:%d:%s]:" FMT "\n", basename(__FILE__), __LINE__, __FUNCTION__, ## __VA_ARGS__)
                                                                                                          ^
    <scratch space>:55:1: note: expanded from here
    "ndsi/h264/mp4_writer.cpp"
    ^
    ndsi/h264/mp4_writer.cpp:234:11: error: no member named 'shrink_to_fit' in 'std::vector<serenegiant::media::MediaStream *, std::allocator<serenegiant::media::MediaStream *> >'
                    streams.shrink_to_fit();
                    ~~~~~~~ ^
    13 warnings and 1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1
```
(I tried not only clang but gcc too)

```
gcc --version
gcc (Homebrew GCC 7.3.0_1) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
```

Python 3.6.4 (also tried Python 3.5)
MacOS 10.13.4 and 10.11.6

**Comment by papr** [comment] 2018-05-02 09:25
Closing as a duplicate of https://github.com/pupil-labs/pyndsi/issues/35

**Closed by papr** 2018-05-02 09:25 UTC
