### ISSUE TITLE
Screen Calibration not working

### ISSUE THREAD

**Issue by shrutiashi** [pupil-labs/pupil#779] opened 2017-08-02 17:29 UTC
I installed new release of pupil apps (v0913_macos) on my mac. I have Realsense R200 RGBD camera.
The world camera screen is solid grey with no feed.
After starting screen marker calibration with fake capture screen, it will initiate the calibration screen with white background and black marker. The marker would not move for further calibration. It should be starting 5 point or 9 point calibration but the screen gets stuck on just one position.

To exit the calibration screen I have to click 5 times. "Touch 4 more time to cancel calibration"

<img width="1280" alt="screen shot 2017-08-02 at 1 25 12 pm" src="https://user-images.githubusercontent.com/18153617/28886101-3f9923c2-7786-11e7-8e73-75cb97ea305b.png">

How to get the calibration to work properly?

**Comment by papr** [comment] 2017-08-02 17:35
Dear @shrutiashi 
The calibration procedure only moves on if the calibration marker has been detected. This is only possible if Capture receives a valid world video stream. `Fake Capture` does not provide such.

See [this comment](https://github.com/pupil-labs/pupil/issues/767#issuecomment-316302340) on how to get the R200 working from source for now. We will merge and publish a release soon that includes R200 support.

I will close this issue due to being a duplicate of #767

**Comment by papr** [comment] 2017-08-02 17:36
See the Pupil Docs for further information on how to use Pupil Capture: https://docs.pupil-labs.com/master/#capture-workflow

**Closed by papr** 2017-08-02 17:35 UTC

**Comment by shrutiashi** [comment] 2017-08-02 17:39
Thank you! waiting for the release.

**Comment by choisuyeon** [comment] 2018-11-21 15:56
If you want calibration without world camera, try [pypupil](https://github.com/choisuyeon/pypupil).
