### ISSUE TITLE
Batch Exporter crashes Pupil Player in Windows

### ISSUE THREAD

**Issue by ogik13** [pupil-labs/pupil#558] opened 2016-12-21 19:25 UTC
i was very excited to try this plug-in because it is very time-saving, as opposed to exporting every trial individually. However, sadly, Pupil Player crashes when setting the source and destination directories for Batch Exporter plug-in. It doesn't even start exporting the data.

**Comment by willpatera** [comment] 2016-12-22 04:00
Hi @ogik13 - thanks for the report. This is likely a python3 bug. I will investigate and hopefully be able to fix it today and re-release a bundle.

**Comment by willpatera** [comment] 2016-12-22 07:49
Hi @ogik13 - Please download the latest Pupil Player bundle [here](https://github.com/pupil-labs/pupil/releases/tag/v0.8.7-w#downloads). The issue should be fixed now. 

The Batch Exporter plugin for Pupil Player was tested with this bundle on Windows 10 and in our tests is working. Please make sure to use the correct path separator for windows file paths 👉  `\`  (Example: `C:\Users\UserName\recordings\`)

Let us know if the issue is resolved.

**Comment by willpatera** [comment] 2016-12-23 10:29
@ogik13 - I am closing this now because our tests show this as being resolved. Please re-open or comment if it does not resolve your issue with further information about what triggers the issue.

**Closed by willpatera** 2016-12-23 10:29 UTC
Labels: bug, python3, Windows

**Comment by ogik13** [comment] 2016-12-23 22:08
Hi Will,

The batch exporter was not crashing this time. However, after several seconds I get an error and the process stops. 
An example of the errors is:

Player [ERROR] libav.mpeg4 : Invalid pts (34864) <= last (34864)
Process Export_Process-110:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 249, in _bootstrap
  File "multiprocessing\process.py", line 93, in run
  File "exporter.py", line 182, in export
  File "av_writer.py", line 142, in write_video_frame
  File "av\video\stream.pyx", line 86, in av.video.stream.VideoStream.encode (src\av\video\stream.c:2806)
  File "av\video\stream.pyx", line 147, in av.video.stream.VideoStream.encode (src\av\video\stream.c:2496)
  File "av\utils.pyx", line 78, in av.utils.err_check (src\av\utils.c:1539)
av.AVError: [Errno 1] Operation not permitted

After this, only mp4 video files are exported and nothing else. 
The plug-ins that are on are: manual gaze correction, gaze cross (or circle), gaze polyline, raw data exporter, and scan path..

**Comment by mkassner** [comment] 2016-12-24 12:35
This issue comes from the coarse resolution of the windows uvc time source.

It's not a bug of the exporter but need to be fixed in libuvc

M
