### ISSUE TITLE
trim_marks "invalid operation" GLError in Player

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil#536] opened 2016-11-30 16:07 UTC
Steps:

1. Open recording
2. Open Offline Surface Detector
3. Add new surface
4. Crash at the end of surface learning procedure

Not reproducible. 😢 

Stacktrace:
```
Traceback (most recent call last):
  File "main.py", line 581, in <module>
    session(this_session_dir)
  File "main.py", line 461, in session
    p.gl_display()
  File ".../pupil_src/player/trim_marks.py", line 150, in gl_display
    glMatrixMode(GL_PROJECTION)
  File "/Library/Python/2.7/site-packages/OpenGL/error.py", line 232, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
	err = 1282,
	description = 'invalid operation',
	baseOperation = glMatrixMode,
	cArguments = (GL_PROJECTION,)
)
```

**Comment by swilmet-ucl** [comment] 2016-12-13 14:12
I have similar errors with Pupil Capture, 100% reproducible for me, with the Docker container based on Fedora 24:

https://github.com/UCL-CATL/docker-pupil

```
Process world:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/root/pupil/pupil_src/capture/world.py", line 495, in world
    glFlush()
  File "errorchecker.pyx", line 53, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError (src/errorchecker.c:1218)
GLError: GLError(
	err = 1281,
	description = 'invalid value',
	baseOperation = glFlush,
	cArguments = ()
)

[...]

Process eye0:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/root/pupil/pupil_src/capture/eye.py", line 478, in eye
    clear_gl_screen()
  File "/root/pupil/pupil_src/shared_modules/gl_utils/utils.py", line 66, in clear_gl_screen
    glClear(GL_COLOR_BUFFER_BIT)
  File "errorchecker.pyx", line 53, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError (src/errorchecker.c:1218)
GLError: GLError(
	err = 1281,
	description = 'invalid value',
	baseOperation = glClear,
	cArguments = (GL_COLOR_BUFFER_BIT,)
)
```

The only thing I know is that it worked fine with Pupil 0.7.6. I have updated to 0.8.6 and 0.8.7 recently, and I now always have the above errors when the webcams are not connected (so it should use the fake capture).

**Comment by mkassner** [comment] 2017-02-21 08:23
I think this is resolved with the latest version of Pupil

**Closed by mkassner** 2017-02-21 08:23 UTC

**Comment by swilmet-ucl** [comment] 2017-02-23 11:38
I no longer have the above problem with the latest version, so it seems to be fixed, thanks.

**Comment by mkassner** [comment] 2017-02-23 13:33
great!!!
