### ISSUE TITLE
Error in building pupil_detectors setup.py

### ISSUE THREAD

**Issue by behrooza** [pupil-labs/pupil#1331] opened 2018-10-16 10:54 UTC
I got the following error while I was trying to build setup.py in "pupil/pupil_src/shared_modules/pupil_detectors" :
cl : Command line warning D9025 : overriding '/W3' with '/w'
cl : Command line warning D9002 : ignoring unknown option '-std=c++17'
detector_2d.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include\type_traits(1271): error C2338: You've instantiated std::aligned_storage<Len, Align> with an extended alignment (in other words, Align > alignof(max_align_t)). Before VS 2017 15.8, the member type would non-conformingly have an alignment of only alignof(max_align_t). VS 2017 15.8 was fixed to handle this correctly, but the fix inherently changes layout and breaks binary compatibility (*only* for uses of aligned_storage with extended alignments). Please define either (1) _ENABLE_EXTENDED_ALIGNED_STORAGE to acknowledge that you understand this message and that you actually want a type with an extended alignment, or (2) _DISABLE_EXTENDED_ALIGNED_STORAGE to silence this message and get the old non-conformant behavior.
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include\type_traits(1291): note: see reference to class template instantiation 'std::_Aligned<144,16,double,false>' being compiled
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include\type_traits(1298): note: see reference to class template instantiation 'std::_Aligned<144,16,int,false>' being compiled
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include\type_traits(1305): note: see reference to class template instantiation 'std::_Aligned<144,16,short,false>' being compiled
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include\type_traits(1312): note: see reference to class template instantiation 'std::_Aligned<144,16,char,false>' being compiled
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include\type_traits(1320): note: see reference to class template instantiation 'std::aligned_storage<144,16>' being compiled
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include\type_traits(1352): note: see reference to alias template instantiation 'aligned_storage_t<144,16>' being compiled
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include\type_traits(1357): note: see reference to class template instantiation 'std::aligned_union<1,_Ty>' being compiled
        with
        [
            _Ty=singleeyefitter::Detector2DResult
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include\memory(1820): note: see reference to alias template instantiation 'aligned_union_t<1,singleeyefitter::Detector2DResult>' being compiled
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include\memory(1866): note: see reference to class template instantiation 'std::_Ref_count_obj<_Ty>' being compiled
        with
        [
            _Ty=singleeyefitter::Detector2DResult
        ]
c:\work\pupil\pupil_src\shared_modules\pupil_detectors\detect_2d.hpp(76): note: see reference to function template instantiation 'std::shared_ptr<singleeyefitter::Detector2DResult> std::make_shared<singleeyefitter::Detector2DResult,>(void)' being compiled
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

it seems that I have to define _ENABLE_EXTENDED_ALIGNED_STORAGE somewhere but I dont know where!!
I am using python 3.6.6 and Visual Studio 2017 15.8!
I was wondering whether anybody could run pupil lab from source on Windows!! :-?

Thanks for your kind help :)

**Comment by stevcode** [comment] 2018-10-16 22:06
I too ran across this issue and have "fixed" it. The issue does stem from the recent Visual Studio 2017 v15.8 update. There are 3 files the following line of code needs to be added to:

`#define _ENABLE_EXTENDED_ALIGNED_STORAGE`

The 3 files are:

/pupil_src/shared_modules/pupil_detectors/detector_2d.cpp
/pupil_src/shared_modules/pupil_detectors/detector_3d.cpp
/pupil_src/shared_modules/pupil_detectors/singleeyefitter/EyeModelFitter.cpp

Adding to EyeModelFitter.cpp is easy, just adding it to the top of the file.

The other 2 files do not exist in source code though. They are auto-generated by: 

/pupil_src/shared_modules/pupil_detectors/detector_2d.pyx
/pupil_src/shared_modules/pupil_detectors/detector_3d.pyx

These 2 Cython files auto-generate their respective .cpp files, but when other files try to utilize detector_2d.cpp or detector_3d.cpp, they run into this issue. You can just add the #define code to the top of those 2 files and the build process will work as intended. However, the two .cpp aren't part of the source code, so if you re-download from source, or try to do a clean build, you have to manually go in and edit the .cpp files again.

The fix for this issue is to modify the Cython code in detector_2d.pyx and detector_3d.pyx so that their auto-generated .cpp files include the line `#define _ENABLE_EXTENDED_ALIGNED_STORAGE`. I just haven't been able to figure out how to do this, due to my unfamiliarity with Cython.

**Comment by behrooza** [comment] 2018-10-17 07:44
Thank you so much! It is working now.

I think some lines of code should be added to check the MSVC version and then define _ENABLE_EXTENDED_ALIGNED_STORAGE based on the MSVC version!!

**Closed** 2018-10-17 07:44 UTC

**Comment by pfaion** [comment] 2019-09-25 13:14
I just found this: https://forum.kde.org/viewtopic.php?f=74&t=153982#p403891
Reference for when we are adding this to the actual build soonish.
