### ISSUE TITLE
Pupil Capture Crashing - Ubuntu Machine

### ISSUE THREAD

**Issue by matmill5** [pupil-labs/pupil#1684] opened 2019-10-14 20:03 UTC
Capture application is not working.  Here is the capture.log file's contents.  Please let me know.

```
2019-10-14 15:55:07,357 - MainProcess - [DEBUG] root: Unknown command-line arguments: []
2019-10-14 15:55:07,358 - MainProcess - [DEBUG] os_utils: Disabling idle sleep not supported on this OS version.
2019-10-14 15:55:07,684 - world - [INFO] launchables.world: Application Version: 1.16.80
2019-10-14 15:55:07,684 - world - [INFO] launchables.world: System Info: User: matthew, Platform: Linux, Machine: Bizon-DevBOX, Release: 4.15.0-65-generic, Version: #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019
2019-10-14 15:55:07,810 - world - [INFO] video_capture: Install pyrealsense to use the Intel RealSense backend
2019-10-14 15:55:08,064 - world - [DEBUG] pupil_apriltags: Testing possible hit: /opt/pupil_capture/pupil_apriltags/lib/libapriltag.so...
2019-10-14 15:55:08,064 - world - [DEBUG] pupil_apriltags: Found working clib at /opt/pupil_capture/pupil_apriltags/lib/libapriltag.so
2019-10-14 15:55:08,233 - world - [DEBUG] plugin: Loading plugin: UVC_Source with settings {'frame_size': [1280, 720], 'frame_rate': 30, 'check_stripes': True, 'exposure_mode': 'manual', 'preferred_names': ['Pupil Cam1 ID2', 'Logitech Camera', '(046d:081d)', 'C510', 'B525', 'C525', 'C615', 'C920', 'C930e']}
2019-10-14 15:55:09,241 - world - [ERROR] video_capture.uvc_backend: Init failed. Capture is started in ghost mode. No images will be supplied.
2019-10-14 15:55:09,242 - world - [INFO] camera_models: No user calibration found for camera Ghost capture at resolution [1280, 720]
2019-10-14 15:55:09,242 - world - [INFO] camera_models: No pre-recorded calibration available
2019-10-14 15:55:09,242 - world - [WARNING] camera_models: Loading dummy calibration
2019-10-14 15:55:09,242 - world - [DEBUG] plugin: Loading plugin: Pupil_Data_Relay with settings {}
2019-10-14 15:55:09,243 - world - [DEBUG] plugin: Loading plugin: Pupil_Remote with settings {'port': 50020, 'host': '0.0.0.0', 'use_primary_interface': True}
2019-10-14 15:55:09,248 - world - [DEBUG] plugin: Loading plugin: Dummy_Gaze_Mapper with settings {}
2019-10-14 15:55:09,249 - world - [DEBUG] plugin: Loading plugin: Log_Display with settings {}
2019-10-14 15:55:09,251 - world - [DEBUG] plugin: Loading plugin: Screen_Marker_Calibration with settings {'fullscreen': True, 'marker_scale': 1.0, 'monitor_idx': 0}
2019-10-14 15:55:09,252 - world - [DEBUG] plugin: Loading plugin: Plugin_Manager with settings {}
2019-10-14 15:55:09,253 - world - [DEBUG] plugin: Loading plugin: System_Graphs with settings {'show_cpu': True, 'show_fps': True, 'show_conf0': True, 'show_conf1': True, 'show_dia0': False, 'show_dia1': False}
2019-10-14 15:55:09,256 - world - [DEBUG] plugin: Loading plugin: Eye_Movement_Detector_Real_Time with settings {}
2019-10-14 15:55:09,256 - world - [DEBUG] plugin: Loading plugin: File_Manager with settings {'root_folder': '/home/matthew/recordings'}
2019-10-14 15:55:09,257 - world - [DEBUG] plugin: Loading plugin: Display_Recent_Gaze with settings {}
2019-10-14 15:55:09,257 - world - [DEBUG] plugin: Loading plugin: Accuracy_Visualizer with settings {'outlier_threshold': 5.0, 'vis_mapping_error': True, 'vis_calibration_area': True}
2019-10-14 15:55:09,257 - world - [DEBUG] plugin: Loading plugin: Blink_Detection with settings {'history_length': 0.2, 'visualize': True, 'onset_confidence_threshold': 0.5, 'offset_confidence_threshold': 0.5}
2019-10-14 15:55:09,257 - world - [DEBUG] plugin: Loading plugin: Recorder with settings {'record_eye': True, 'session_name': '2019_10_08', 'user_info': {'name': '', 'additional_field': 'change_me'}, 'info_menu_conf': {}, 'show_info_menu': False, 'rec_root_dir': '/home/matthew/recordings', 'raw_jpeg': True}
2019-10-14 15:55:09,260 - world - [WARNING] launchables.world: Process started.
2019-10-14 15:55:10,151 - eye0 - [INFO] video_capture: Install pyrealsense to use the Intel RealSense backend
2019-10-14 15:55:10,205 - eye0 - [DEBUG] uvc: Found device that mached uid:'1:19'
2019-10-14 15:55:10,289 - eye0 - [DEBUG] uvc: Device '1:19' opended.
2019-10-14 15:55:10,290 - eye0 - [DEBUG] uvc: avaible video modes: [{'size': (400, 400), 'rates': [120, 90, 60, 30]}, {'size': (192, 192), 'rates': [200, 180, 120, 90, 60, 30]}]
2019-10-14 15:55:10,290 - eye0 - [DEBUG] uvc: Adding "Auto Exposure Mode" control.
2019-10-14 15:55:10,292 - eye0 - [DEBUG] uvc: Adding "Auto Exposure Priority" control.
2019-10-14 15:55:10,293 - eye0 - [DEBUG] uvc: Adding "Absolute Exposure Time" control.
2019-10-14 15:55:10,295 - eye0 - [DEBUG] uvc: Adding "Auto Focus" control.
2019-10-14 15:55:10,297 - eye0 - [DEBUG] uvc: Adding "Absolute Focus" control.
2019-10-14 15:55:10,300 - eye0 - [DEBUG] uvc: Adding "Absolute Iris " control.
2019-10-14 15:55:10,303 - eye0 - [DEBUG] uvc: Adding "Scanning Mode " control.
2019-10-14 15:55:10,304 - eye0 - [DEBUG] uvc: Adding "Zoom absolute control" control.
2019-10-14 15:55:10,308 - eye0 - [DEBUG] uvc: Adding "Pan control" control.
2019-10-14 15:55:10,312 - eye0 - [DEBUG] uvc: Adding "Tilt control" control.
2019-10-14 15:55:10,315 - eye0 - [DEBUG] uvc: Adding "Roll absolute control" control.
2019-10-14 15:55:10,319 - eye0 - [DEBUG] uvc: Adding "Privacy Shutter control" control.
2019-10-14 15:55:10,320 - eye0 - [DEBUG] uvc: Adding "Backlight Compensation" control.
2019-10-14 15:55:10,323 - eye0 - [DEBUG] uvc: Adding "Brightness" control.
2019-10-14 15:55:10,326 - eye0 - [DEBUG] uvc: Adding "Contrast" control.
2019-10-14 15:55:10,329 - eye0 - [DEBUG] uvc: Adding "Gain" control.
2019-10-14 15:55:10,333 - eye0 - [DEBUG] uvc: Adding "Power Line frequency" control.
2019-10-14 15:55:10,334 - eye0 - [DEBUG] uvc: Adding "Hue" control.
2019-10-14 15:55:10,338 - eye0 - [DEBUG] uvc: Adding "Saturation" control.
2019-10-14 15:55:10,341 - eye0 - [DEBUG] uvc: Adding "Sharpness" control.
2019-10-14 15:55:10,344 - eye0 - [DEBUG] uvc: Adding "Gamma" control.
2019-10-14 15:55:10,347 - eye0 - [DEBUG] uvc: Adding "White Balance temperature" control.
2019-10-14 15:55:10,350 - eye0 - [DEBUG] uvc: Adding "White Balance temperature,Auto" control.
2019-10-14 15:55:10,359 - eye1 - [INFO] video_capture: Install pyrealsense to use the Intel RealSense backend
2019-10-14 15:55:10,368 - eye0 - [INFO] camera_models: No user calibration found for camera Pupil Cam2 ID0 at resolution (192, 192)
2019-10-14 15:55:10,369 - eye0 - [INFO] camera_models: No pre-recorded calibration available
2019-10-14 15:55:10,369 - eye0 - [WARNING] camera_models: Loading dummy calibration
2019-10-14 15:55:10,369 - eye0 - [DEBUG] uvc: Setting mode: 192,192,120
2019-10-14 15:55:10,431 - eye1 - [DEBUG] uvc: Found device that mached uid:'1:20'
2019-10-14 15:55:10,485 - eye0 - [WARNING] uvc: Could not set Value. 'Backlight Compensation'.
2019-10-14 15:55:10,494 - eye1 - [DEBUG] uvc: Device '1:20' opended.
2019-10-14 15:55:10,494 - eye1 - [DEBUG] uvc: avaible video modes: [{'size': (400, 400), 'rates': [120, 90, 60, 30]}, {'size': (192, 192), 'rates': [200, 180, 120, 90, 60, 30]}]
2019-10-14 15:55:10,494 - eye1 - [DEBUG] uvc: Adding "Auto Exposure Mode" control.
2019-10-14 15:55:10,496 - eye1 - [DEBUG] uvc: Adding "Auto Exposure Priority" control.
2019-10-14 15:55:10,497 - eye1 - [DEBUG] uvc: Adding "Absolute Exposure Time" control.
2019-10-14 15:55:10,500 - eye1 - [DEBUG] uvc: Adding "Auto Focus" control.
2019-10-14 15:55:10,502 - eye1 - [DEBUG] uvc: Adding "Absolute Focus" control.
2019-10-14 15:55:10,505 - eye1 - [DEBUG] uvc: Adding "Absolute Iris " control.
2019-10-14 15:55:10,509 - eye1 - [DEBUG] uvc: Adding "Scanning Mode " control.
2019-10-14 15:55:10,510 - eye1 - [DEBUG] uvc: Adding "Zoom absolute control" control.
2019-10-14 15:55:10,513 - eye1 - [DEBUG] uvc: Adding "Pan control" control.
2019-10-14 15:55:10,516 - eye1 - [DEBUG] uvc: Adding "Tilt control" control.
2019-10-14 15:55:10,520 - eye1 - [DEBUG] uvc: Adding "Roll absolute control" control.
2019-10-14 15:55:10,523 - eye1 - [DEBUG] uvc: Adding "Privacy Shutter control" control.
2019-10-14 15:55:10,524 - eye1 - [DEBUG] uvc: Adding "Backlight Compensation" control.
2019-10-14 15:55:10,528 - eye1 - [DEBUG] uvc: Adding "Brightness" control.
2019-10-14 15:55:10,531 - eye1 - [DEBUG] uvc: Adding "Contrast" control.
2019-10-14 15:55:10,534 - eye1 - [DEBUG] uvc: Adding "Gain" control.
2019-10-14 15:55:10,538 - eye1 - [DEBUG] uvc: Adding "Power Line frequency" control.
2019-10-14 15:55:10,540 - eye1 - [DEBUG] uvc: Adding "Hue" control.
2019-10-14 15:55:10,543 - eye1 - [DEBUG] uvc: Adding "Saturation" control.
2019-10-14 15:55:10,546 - eye1 - [DEBUG] uvc: Adding "Sharpness" control.
2019-10-14 15:55:10,549 - eye1 - [DEBUG] uvc: Adding "Gamma" control.
2019-10-14 15:55:10,553 - eye1 - [DEBUG] uvc: Adding "White Balance temperature" control.
2019-10-14 15:55:10,556 - eye1 - [DEBUG] uvc: Adding "White Balance temperature,Auto" control.
2019-10-14 15:55:10,574 - eye1 - [INFO] camera_models: No user calibration found for camera Pupil Cam2 ID1 at resolution (192, 192)
2019-10-14 15:55:10,574 - eye1 - [INFO] camera_models: No pre-recorded calibration available
2019-10-14 15:55:10,574 - eye1 - [WARNING] camera_models: Loading dummy calibration
2019-10-14 15:55:10,575 - eye1 - [DEBUG] uvc: Setting mode: 192,192,120
2019-10-14 15:55:10,680 - eye1 - [WARNING] uvc: Could not set Value. 'Backlight Compensation'.
2019-10-14 15:55:11,004 - eye0 - [WARNING] launchables.eye: Process started.
2019-10-14 15:55:11,074 - eye0 - [DEBUG] uvc: Stream start.
2019-10-14 15:55:11,106 - eye0 - [WARNING] video_capture.uvc_backend: Received frame with invalid timestamp. This can happen after a disconnect. Frame will be dropped!
2019-10-14 15:55:11,612 - eye1 - [WARNING] launchables.eye: Process started.
2019-10-14 15:55:11,677 - eye1 - [DEBUG] uvc: Stream start.
2019-10-14 15:55:11,705 - eye1 - [WARNING] video_capture.uvc_backend: Received frame with invalid timestamp. This can happen after a disconnect. Frame will be dropped!
2019-10-14 15:55:11,736 - world - [DEBUG] blink_detection: Blink onset detected with confidence 1.000
2019-10-14 15:55:11,758 - world - [DEBUG] blink_detection: Blink onset detected with confidence 0.556
2019-10-14 15:55:11,978 - world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "launchables/world.py", line 652, in world
  File "OpenGL/error.py", line 232, in glCheckError
OpenGL.error.GLError: GLError(
	err = 1281,
	description = b'invalid value',
	baseOperation = glViewport,
	cArguments = (0, 0, 927, 1023)
)

2019-10-14 15:55:11,978 - world - [INFO] launchables.world: Process shutting down.
2019-10-14 15:55:12,274 - eye0 - [DEBUG] uvc: Stream stopped
2019-10-14 15:55:12,307 - eye0 - [DEBUG] uvc: Stream closed
2019-10-14 15:55:12,307 - eye0 - [DEBUG] uvc: Stream stop.
2019-10-14 15:55:12,345 - eye0 - [DEBUG] uvc: UVC device closed.
2019-10-14 15:55:12,353 - eye0 - [INFO] launchables.eye: Process shutting down.
2019-10-14 15:55:12,486 - eye1 - [DEBUG] uvc: Stream stopped
2019-10-14 15:55:12,520 - eye1 - [DEBUG] uvc: Stream closed
2019-10-14 15:55:12,520 - eye1 - [DEBUG] uvc: Stream stop.
2019-10-14 15:55:12,535 - eye1 - [DEBUG] uvc: UVC device closed.
2019-10-14 15:55:12,579 - eye1 - [INFO] launchables.eye: Process shutting down.

```

**Comment by pfaion** [comment] 2019-10-15 07:00
Hi @matmill5 
did it work before on your machine or this is a first use?
What specific operating system are you using?
Are you running from bundle, or from source?
Please try deleting your capture settings folder. If you are running from bundle, you will find it in your home folder.

**Comment by pfaion** [comment] 2019-10-15 07:04
This seems to be a duplicate of #1284 
The user there reported that it did happen very rarely and that they couldn't reproduce the issue.
Since it happened again now we will investigate this again.
Thanks for reporting the issue!

**Closed by pfaion** 2019-10-15 07:04 UTC
Labels: duplicate
