### ISSUE TITLE
Can't run from source

### ISSUE THREAD

**Issue by Luisaply** [pupil-labs/pupil#1282] opened 2018-08-29 09:02 UTC
Hello,
I tried to run the software from source on Windows. But it comes to this error:

`C:\Python36\python.exe C:/work/pupil/pupil_src/main.py
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
world - [INFO] launchables.world: Application Version: 1.8.33
world - [INFO] launchables.world: System Info: User: uwebk, Platform: Windows, Machine: itiv-3071, Release: 10, Version: 10.0.17134
world - [INFO] pupil_detectors.build: Building extension modules...
cl : Befehlszeile warning D9025 : "/W3" wird durch "/w" �berschrieben
cl : Befehlszeile warning D9002 : Unbekannte Option "-std=c++11" wird ignoriert.
cl : Befehlszeile warning D9025 : "/W3" wird durch "/w" �berschrieben
cl : Befehlszeile warning D9002 : Unbekannte Option "-std=c++11" wird ignoriert.
cl : Befehlszeile warning D9025 : "/W3" wird durch "/w" �berschrieben
cl : Befehlszeile warning D9002 : Unbekannte Option "-std=c++11" wird ignoriert.
cl : Befehlszeile warning D9025 : "/W3" wird durch "/w" �berschrieben
cl : Befehlszeile warning D9002 : Unbekannte Option "-std=c++11" wird ignoriert.
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1104
world - [ERROR] launchables.world: Process Capture crashed with trace:
Traceback (most recent call last):
  File "C:\work\pupil\pupil_src\launchables\world.py", line 113, in world
    import pupil_detectors
  File "C:\work\pupil\pupil_src\shared_modules\pupil_detectors\__init__.py", line 16, in <module>
    build_cpp_extension()
  File "C:\work\pupil\pupil_src\shared_modules\pupil_detectors\build.py", line 25, in build_cpp_extension
    ret = sp.check_output(build_cmd).decode(sys.stdout.encoding)
  File "C:\Python36\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "C:\Python36\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\Python36\\python.exe', 'setup.py', 'install', '--install-lib=C:\\work\\pupil\\pupil_src\\shared_modules']' returned non-zero exit status 1.

world - [INFO] launchables.world: Process shutting down.
`
can anyone help me?

**Comment by papr** [comment] 2018-08-29 10:04
Duplicate of #1269

**Closed** 2018-08-29 10:04 UTC

**Comment by papr** [comment] 2018-08-29 10:27
In this case you will need to follow the first part of this comment https://github.com/pupil-labs/pupil/issues/1269#issuecomment-413476281

**Comment by papr** [comment] 2018-08-29 10:28
BTW, why do you need to run from source? Can't you use the bundled applications?

**Comment by Luisaply** [comment] 2018-08-29 11:45
Because i need to integrate the eye tracking algorithms into existing solutions for my thesis.
I think the problem can be the incorrect bild of libglog_static and ceres_static in ceres_windows. Yet i don't know how to solve it. I downloaded the Visual Studio 2017 Preview 15.9 instead of 15.3 , and the runtimes and components for development in the Workloads tab are not exactly the same with required. For example, there are no
MFC and ALT support(x86, x64)
VC++ 2017 v141 toolset (x86,x64)
in 15.9 version, so i downloaded instead 
 Visual C++-ATL für x86 und x64
 Visual C++ ATL für ARM
 Visual C++ ATL für ARM64
 Visual C++ ATL (x86/x64) mit Spectre-Entschärfungen
 Visual C++ ATL für ARM mit Spectre-Entschärfungen
 Visual C++ ATL für ARM64 mit Spectre-Entschärfungen
 Visual C++ MFC für x86/x64 mit Spectre-Entschärfungen
 Visual C++ MFC für ARM mit Spectre-Entschärfungen
 Visual C++-MFC-Unterstützung für ARM64 mit Spectre-Entschärfungen
 Visual C++ MFC für ARM
 Visual C++ MFC für ARM64
 Neueste v141-Tools in VC++ 2017, Version 15.8 v14.15
 VC++ 2017 version 15.7 v14.14 toolset
 Toolset für VC++ 2017, Version 15.6 v14.13
 Toolset für VC++ 2017, Version 15.5 v14.12
 Toolset für VC++ 2017, Version 15.4 v14.11

Is that the reason that some files can't be compiled? How can i solve it?

**Comment by papr** [comment] 2018-08-29 11:52
Unfortunately, I am not able to help you with this since I do not have much experience with the Windows source setup. I know that it is very tedious to get it running. This is why we highly recommend to find alternative solutions:

My I recommend our zmq network API for your integration task? You can start/stop recording/calibration as well as subscribe to the real-time data stream using this method. Does this satisfy your requirements?

**Comment by Luisaply** [comment] 2018-08-29 12:03
Thank you very much!  I will contact my supervisor and have a try.

**Comment by Luisaply** [comment] 2018-08-29 12:42
Hallo @papr ,
Could you please tell me how to use the zmq network API? Should i install it in another system like Linux?
My supervisor means, he would prefer to run it in the windows system. Is it still possible to handle it?

**Comment by papr** [comment] 2018-08-29 12:47
Hey @Luisaply 
Yes, this is possible. This is how the setup would look like.
1. You run the [bundled Capture application](https://github.com/pupil-labs/pupil/releases)
1. You run your custom application that uses the [network interface](https://docs.pupil-labs.com/#interprocess-and-network-communication). This application can either run on the same computer as in step 1 or on a different computer in the same network.

See this example python script that uses the network api: https://github.com/pupil-labs/pupil-helpers/blob/master/python/pupil_remote_control.py

**Comment by Luisaply** [comment] 2018-08-30 13:12
Hello @papr ,
I really appreciate your help! 
One more question, if i want to combine some simulation of eye illnesses with the eye tracking algorithms, do i still need to use a network API? Can i write it as a plugin and put it into pupil_capture_settings/plugins/? Because i thought maybe i don't need it if i don't want to send data to a second device.

**Comment by papr** [comment] 2018-08-30 13:15
How would simulate the eye illness? Do you want to pipe video renderings of these simulations into Capture?

**Comment by Luisaply** [comment] 2018-08-30 13:34
There are some simulation algorithms from my college and my work will be integrating them to the eye tracking algorithms and representing it in real time video.

**Comment by papr** [comment] 2018-08-30 13:41
So if I understood you correctly, one way would be to build a custom video backend that pipes the simualtions into Capture. These are the existing video backends: https://github.com/pupil-labs/pupil/tree/master/pupil_src/shared_modules/video_capture
