### ISSUE TITLE
Pupil Player v0.9.5 on Mac hangs indefinitely on video export 

### ISSUE THREAD

**Issue by jonmatthis** [pupil-labs/pupil#704] opened 2017-04-15 00:40 UTC
The new version doesn't crash (as referenced in https://github.com/pupil-labs/pupil/issues/693), but it does hang indefinitely. Clicking export causes the progress bar to show up, but it never gets past 0. 

Running on OSX 10.11.4 on a MacBook Pro

**Comment by willpatera** [comment] 2017-04-16 08:57
@mkassner sounds like PyInstaller multiprocessing issue.

**Comment by mkassner** [comment] 2017-04-16 09:17
Have you given the export some time? I noticed that it takes a while
especially with small ram machines.

I ll have a look as well.

**Comment by jonmatthis** [comment] 2017-04-18 18:14
Yes, of course. Even after an hour or so, the frame # remains at 0. I have made dozens of these movies at this point, so I can tell the difference between "this is taking a long time" vs "this is not doing anything"

**Comment by mkassner** [comment] 2017-04-19 18:42
Ok. I ll have a look and resolve this tomorrow. Could you share one of your recordings in case I cannot reproduce?

**Comment by xiaoxuefu** [comment] 2017-04-19 23:07
Hi Moritz,

I would like to chime in this thread, as we are also having exporting issues using Pupil Player v0.9.5. I attached a screenshot to help describe the problem. In this case, when we just added one Gaze Circle plugin, the export stopped at 6989 frames. For our formal data processing, we would like to have 3 Gaze Circles (with different radius), Gaze Cross,  and Eye Video Overlay. When we added all these plugins, the frame # remains at 0 as jonmatthis posted. We also tried to export only a few frames of our recording, it also didn't work. Our export failed with the latest version of Pupil Player installed on OSX, windows, and Ubuntu. 

Thank you very much in advance for helping resolving the issue!


![screen shot 2017-04-19 at 3 58 10 pm](https://cloud.githubusercontent.com/assets/13022157/25205660/c051791c-2531-11e7-8a5d-1d15bd996e6b.png)

**Comment by mkassner** [comment] 2017-04-20 09:40
@xiaoxuefu the export stopping midway might be a different issue. What hardware are you using? What OS was the recording done with? Usually a stop like this comes from two frames in a recording having the same timestamp. Can you send the world_timestamps.npy file that came with this recording?

@jonmatthis  I have the issue of exports not starting on macos resolved and will upload a new release in a few mins. Btw what plugins where active when you start the export?

**Comment by mkassner** [comment] 2017-04-20 13:01
@jonmatthis  I just pushed a release please try and report back!

@xiaoxuefu  please make a new issue for the export hanging at a certain number and add the world_timestamps.npy file.

**Comment by jonmatthis** [comment] 2017-04-20 13:57
Excellent! I will try the new release and let you know how it works. 

Regarding your question on the plugins - I believe I was running - vis cross, vis circle, viz polyline (?), eye video overlay, manual gaze correction, raw data exporter, and video exporter.

**Comment by mkassner** [comment] 2017-04-20 15:54
According to @xiaoxuefu  this issue is fixed.

**Closed by mkassner** 2017-04-20 15:54 UTC

**Comment by jonmatthis** [comment] 2017-04-20 17:17
I can confirm that! Seems to be working perfectly on my end. 

Thank you!
