### ISSUE TITLE
Wiki: Developer setup misses potential error (opencv3 - python3 binding)

### ISSUE THREAD

**Issue by dalind** [pupil-labs/pupil#606] opened 2017-01-31 17:43 UTC
I spent the last day figuring out why I could not build the pupil source on one Mac, while it worked nicely on another. The problem was that I was not able to import cv2 with python3 (ModuleNotFound).

It turns out cv2.so in /usr/local/opt/opencv3/lib/python3.6/site-packages/ got renamed to something weird (cv2.cpython-35m-darwin.so) while installing opencv3. I did not have the issue on my MacBook, only on a different Mac machine.

The problem is described in "Handling the Python 3 issue"  at http://www.pyimagesearch.com/2016/12/19/install-opencv-3-on-macos-with-homebrew-the-easy-way/ 

The fix is to rename cv2.cpython-35m-darwin.so to cv2.so and then to link the path:
`echo /usr/local/opt/opencv3/lib/python3.6/site-packages >> /usr/local/lib/python3.6/site-packages/opencv3.pth`

While I know this isn't a Pupil problem, it would be worth adding to https://github.com/pupil-labs/pupil/wiki/Dependencies-Installation-MacOS

**Comment by mkassner** [comment] 2017-01-31 18:03
While this might fix the problem renaming the fully qualified library name is not the right approach. My guess is that `cv2.cpython-35m-darwin.so ` was built for python3.5 and not for 3.6. Do you have python3.5 installed next to python3.6?  I recommend removing one of the two and reinstalling opencv3.

**Comment by dalind** [comment] 2017-01-31 18:07
The name `cv2.cpython-35m-darwin.so` was actually copied from the blog. I renamed mine, so I don't know the exact name. I started with a completely fresh system today (as in: I wiped my computer), and followed your guide very closely. I only have python2.7 installed (Mac OS default). 

Since the problem did not happen on my Macbook (same configuration), I guess the problem might just occur due to some opencv3 weirdness. 

I would still point people to the blog and highlight the problem. Could save quite some time. Renaming might not be optimal solution, I agree, however a good quick fix.

**Comment by matiarj** [comment] 2017-01-31 20:45
I'm getting the same issue however I cannot find the following path

/usr/local/opt/opencv3/lib/python3.6/site-packages/
i instead have
/usr/local/opt/opencv3/lib/ a bunch of .dylib files and pkgconfig which has opencv.pc inside

I still cannot get any of my macs to run from source i continually keep running into 

 import cv2
ModuleNotFoundError: No module named 'cv2'

help....

**Comment by willpatera** [comment] 2017-02-01 04:52
Hi @dalind @matiarj please note that when you `brew install opencv3` with the flags as listed in the [Dependencies with brew](https://github.com/pupil-labs/pupil/wiki/Dependencies-Installation-MacOS#dependencies-with-brew), you will see a `caveats` message at the end of the installation. 

```bash
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

opencv3 and opencv install many of the same files.

If you need Python to find bindings for this keg-only formula, run:
  echo /usr/local/opt/opencv3/lib/python2.7/site-packages >> /usr/local/lib/python2.7/site-packages/opencv3.pth
``` 

Please follow instructions from the brew caveats but change instructions for python3.6 instead of python2.7 like so:

```
echo /usr/local/opt/opencv3/lib/python3.6/site-packages >> /usr/local/lib/python3.6/site-packages/opencv3.pth
```
@dalind - renaming the lib may solve issues, but is not a good long term solution. I suggest restoring the name 

Please give the above a try and let us know if it resolves issues.

**Comment by matiarj** [comment] 2017-02-02 19:12
@willpatera unfortunately that doesn't work I believe the issue is because that path doesn't exist

this is what my path looks like
![image](https://cloud.githubusercontent.com/assets/15369528/22564208/87a35390-e938-11e6-9ed4-cf845fbb52f3.png)

**Comment by mkassner** [comment] 2017-03-01 13:45
Since we cannot reproduce this error and it seems specific to your setup, I m closing the issue.

**Closed by mkassner** 2017-03-01 13:45 UTC
