### ISSUE TITLE
Latest Capture & Player bundles 0.6.10-1 & 0.6-36 Linux don't open.

### ISSUE THREAD

**Issue by Sijben** [pupil-labs/pupil#207] opened 2015-09-28 11:23 UTC
When attemping to open the apps nothing happens. The icon merely flashes light blue/green a few times but nothing opens.

**Comment by mkassner** [comment] 2015-09-28 12:27
Sorry to hear that. 

Could you start the app in terminal using 'pupil_capture' and 'pupil_player' and report the output?
Also, I need the OS version.

**Comment by Sijben** [comment] 2015-09-28 12:53
Running Ubuntu 14.04.1

eyetracker@ubuntuOLF:~$ pupil_capture
Traceback (most recent call last):
  File "<string>", line 82, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-2.1.1dev_67610f2_mod-py2.7.egg/PyInstaller/loader/pyi_importers.py", line 276, in load_module
  File "/home/mkassner/pupil/deploy_capture/build/bundle/out00-PYZ.pyz/eye", line 37, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-2.1.1dev_67610f2_mod-py2.7.egg/PyInstaller/loader/pyi_importers.py", line 276, in load_module
  File "/home/mkassner/pupil/deploy_capture/build/bundle/out00-PYZ.pyz/methods", line 16, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-2.1.1dev_67610f2_mod-py2.7.egg/PyInstaller/loader/pyi_importers.py", line 420, in load_module
ImportError: /usr/lib/x86_64-linux-gnu/libschroedinger-1.0.so.0: undefined symbol: orc_program_new_from_static_bytecode


eyetracker@ubuntuOLF:~$ pupil_player
Traceback (most recent call last):
  File "<string>", line 92, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-2.1.1dev_67610f2_mod-py2.7.egg/PyInstaller/loader/pyi_importers.py", line 276, in load_module
  File "/home/mkassner/pupil/deploy_player/build/bundle/out00-PYZ.pyz/video_capture", line 23, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-2.1.1dev_67610f2_mod-py2.7.egg/PyInstaller/loader/pyi_importers.py", line 420, in load_module
ImportError: /usr/lib/x86_64-linux-gnu/libschroedinger-1.0.so.0: undefined symbol: orc_program_new_from_static_bytecode

**Comment by mkassner** [comment] 2015-09-28 13:03
This is the same error as #196 

is this a 32 or 64 bit system?

**Comment by Sijben** [comment] 2015-09-28 13:12
64 bit

**Comment by mkassner** [comment] 2015-09-28 13:54
Please do `sudo apt-get remove libschroedinger-dev`

The error you are getting is weird because I dont build with
libschroedinger. I suspect that Opencv or FFmpeg but detect this on runtime
and try to load it, but I find this very odd.

**Comment by Sijben** [comment] 2015-09-28 14:35
File not installed and thus not removed. Error remains the same.

In the error message it calls for a folder named mkassner, is this intended?

Defaulting to source version for the moment.

**Comment by mkassner** [comment] 2015-09-28 15:39
The error trace in python shows my paths. This is normal. The offending
line (16 in methods.py) is `import cv2`. From then on `cv2.so` (a bundled
dependency) is loaded which in turn loads a great count of other libraries
and at some point ` /usr/lib/x86_64-linux-gnu/libschroedinger-1.0.so.0`
seems to be requested. This is odd since I dont have this library on the
bundle machine.

We had another user that said this exact same error happens on one of his
14.04 machines but not the others.

While I think this can be resolved by  means of improving the bundle, I
cannot reproduce the error and thus don't know how to debug it.
My suspicion is that some other installed library is interfering. Could you
post the output of:

```
ls /usr/lib/x86_64-linux-gnu/libs*
```

?

**Comment by mkassner** [comment] 2015-09-28 18:24
I will recompile opencv tomorrow and re-bundle. I hope this will help.

**Comment by Sijben** [comment] 2015-10-01 11:11
eyetracker@ubuntuOLF:~$ ls /usr/lib/x86_64-linux-gnu/libs*
/usr/lib/x86_64-linux-gnu/libsamba-credentials.so.0
/usr/lib/x86_64-linux-gnu/libsamba-credentials.so.0.0.1
/usr/lib/x86_64-linux-gnu/libsamba-hostconfig.so.0
/usr/lib/x86_64-linux-gnu/libsamba-hostconfig.so.0.0.1
/usr/lib/x86_64-linux-gnu/libsamba-policy.so.0
/usr/lib/x86_64-linux-gnu/libsamba-policy.so.0.0.1
/usr/lib/x86_64-linux-gnu/libsamba-util.so.0
/usr/lib/x86_64-linux-gnu/libsamba-util.so.0.0.1
/usr/lib/x86_64-linux-gnu/libsamdb.so.0
/usr/lib/x86_64-linux-gnu/libsamdb.so.0.0.1
/usr/lib/x86_64-linux-gnu/libsamplerate.so.0
/usr/lib/x86_64-linux-gnu/libsamplerate.so.0.1.8
/usr/lib/x86_64-linux-gnu/libsane.la
/usr/lib/x86_64-linux-gnu/libsane.so.1
/usr/lib/x86_64-linux-gnu/libsane.so.1.0.23
/usr/lib/x86_64-linux-gnu/libsasl2.so.2
/usr/lib/x86_64-linux-gnu/libsasl2.so.2.0.25
/usr/lib/x86_64-linux-gnu/libsbc.so.1
/usr/lib/x86_64-linux-gnu/libsbc.so.1.1.0
/usr/lib/x86_64-linux-gnu/libschroedinger-1.0.so.0
/usr/lib/x86_64-linux-gnu/libschroedinger-1.0.so.0.11.0
/usr/lib/x86_64-linux-gnu/libsecret-1.so.0
/usr/lib/x86_64-linux-gnu/libsecret-1.so.0.0.0
/usr/lib/x86_64-linux-gnu/libsemanage.so.1
/usr/lib/x86_64-linux-gnu/libsensors.so.4
/usr/lib/x86_64-linux-gnu/libsensors.so.4.3.2
/usr/lib/x86_64-linux-gnu/libshout.so.3
/usr/lib/x86_64-linux-gnu/libshout.so.3.2.0
/usr/lib/x86_64-linux-gnu/libsigc-2.0.so.0
/usr/lib/x86_64-linux-gnu/libsigc-2.0.so.0.0.0
/usr/lib/x86_64-linux-gnu/libsignon-glib.so.1
/usr/lib/x86_64-linux-gnu/libsignon-glib.so.1.0.0
/usr/lib/x86_64-linux-gnu/libsmbclient-raw.so.0
/usr/lib/x86_64-linux-gnu/libsmbclient-raw.so.0.0.1
/usr/lib/x86_64-linux-gnu/libsmbclient.so.0
/usr/lib/x86_64-linux-gnu/libsmbclient.so.0.2.1
/usr/lib/x86_64-linux-gnu/libsmbconf.so.0
/usr/lib/x86_64-linux-gnu/libsmbldap.so.0
/usr/lib/x86_64-linux-gnu/libsmime3.so
/usr/lib/x86_64-linux-gnu/libsndfile.so.1
/usr/lib/x86_64-linux-gnu/libsndfile.so.1.0.25
/usr/lib/x86_64-linux-gnu/libsnmp.so.30
/usr/lib/x86_64-linux-gnu/libsnmp.so.30.0.2
/usr/lib/x86_64-linux-gnu/libsonic.so.0
/usr/lib/x86_64-linux-gnu/libsonic.so.0.1.18
/usr/lib/x86_64-linux-gnu/libsoup-2.4.so.1
/usr/lib/x86_64-linux-gnu/libsoup-2.4.so.1.7.0
/usr/lib/x86_64-linux-gnu/libsoup-gnome-2.4.so.1
/usr/lib/x86_64-linux-gnu/libsoup-gnome-2.4.so.1.7.0
/usr/lib/x86_64-linux-gnu/libspectre.so.1
/usr/lib/x86_64-linux-gnu/libspectre.so.1.1.7
/usr/lib/x86_64-linux-gnu/libspeechd.so.2
/usr/lib/x86_64-linux-gnu/libspeechd.so.2.4.0
/usr/lib/x86_64-linux-gnu/libspeexdsp.so.1
/usr/lib/x86_64-linux-gnu/libspeexdsp.so.1.5.0
/usr/lib/x86_64-linux-gnu/libspeex.so.1
/usr/lib/x86_64-linux-gnu/libspeex.so.1.5.0
/usr/lib/x86_64-linux-gnu/libsqlite3.so.0
/usr/lib/x86_64-linux-gnu/libsqlite3.so.0.8.6
/usr/lib/x86_64-linux-gnu/libssh.so.4
/usr/lib/x86_64-linux-gnu/libssh.so.4.4.0
/usr/lib/x86_64-linux-gnu/libssh_threads.so.4
/usr/lib/x86_64-linux-gnu/libssh_threads.so.4.4.0
/usr/lib/x86_64-linux-gnu/libssl3.so
/usr/lib/x86_64-linux-gnu/libstartup-notification-1.so.0
/usr/lib/x86_64-linux-gnu/libstartup-notification-1.so.0.0.0
/usr/lib/x86_64-linux-gnu/libstdc++.so.6
/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19
/usr/lib/x86_64-linux-gnu/libswscale.a
/usr/lib/x86_64-linux-gnu/libswscale.so
/usr/lib/x86_64-linux-gnu/libswscale.so.2
/usr/lib/x86_64-linux-gnu/libswscale.so.2.1.1


Somehow it does list the libschroedinger in there.

**Comment by mkassner** [comment] 2015-10-01 11:20
Could you try temporarily removing libschroedinger files to see if the
bundle runs then?

Also, if you update from the current master for both pupil and PyAv (dont
forget to rebuild PyAv) you should be able to have the cording play when
running from source.
I have replaced all Opencv media IO with PyAV.

**Comment by Sijben** [comment] 2015-10-01 11:50
Removing the libschroedinger files changes the error to:

eyetracker@ubuntuOLF:~$ pupil_capture
Traceback (most recent call last):
  File "<string>", line 82, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-2.1.1dev_67610f2_mod-py2.7.egg/PyInstaller/loader/pyi_importers.py", line 276, in load_module
  File "/home/mkassner/pupil/deploy_capture/build/bundle/out00-PYZ.pyz/eye", line 37, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-2.1.1dev_67610f2_mod-py2.7.egg/PyInstaller/loader/pyi_importers.py", line 276, in load_module
  File "/home/mkassner/pupil/deploy_capture/build/bundle/out00-PYZ.pyz/methods", line 16, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-2.1.1dev_67610f2_mod-py2.7.egg/PyInstaller/loader/pyi_importers.py", line 420, in load_module
ImportError: libschroedinger-1.0.so.0: cannot open shared object file: No such file or directory



As for the source thing, are you referring to issue #187?  Updated pupil and PyAV yet issue remains.
I'm however in the process of uploading the videos for you and will switch to the smaller file/higher CPU variant. (The " bigger file"  versions are a bit impractical to use anyway at 5 MB per second)

**Comment by mkassner** [comment] 2015-10-01 13:01
Yes, I meant that. It basically means that you are still using an older
version of ffmpeg. I would say, lets ignore your setup for now and just
transcode the videos.

**Comment by mkassner** [comment] 2015-10-01 14:20
Hi,

could you give this bundle a try? https://github.com/pupil-labs/pupil/releases/tag/v0.6.10

**Comment by Sijben** [comment] 2015-10-01 14:46
eyetracker@ubuntuOLF:~$ pupil_capture
Traceback (most recent call last):
  File "<string>", line 82, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-2.1.1dev_67610f2_mod-py2.7.egg/PyInstaller/loader/pyi_importers.py", line 276, in load_module
  File "/home/mkassner/pupil/deploy_capture/build/bundle/out00-PYZ.pyz/eye", line 37, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-2.1.1dev_67610f2_mod-py2.7.egg/PyInstaller/loader/pyi_importers.py", line 276, in load_module
  File "/home/mkassner/pupil/deploy_capture/build/bundle/out00-PYZ.pyz/methods", line 16, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-2.1.1dev_67610f2_mod-py2.7.egg/PyInstaller/loader/pyi_importers.py", line 420, in load_module
ImportError: /opt/pupil_capture/cv2.so: undefined symbol: _ZN2cv11arrowedLineERNS_3MatENS_6Point_IiEES3_RKNS_7Scalar_IdEEiiid


eyetracker@ubuntuOLF:~$ pupil_player
Traceback (most recent call last):
  File "<string>", line 92, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-2.1.1dev_67610f2_mod-py2.7.egg/PyInstaller/loader/pyi_importers.py", line 276, in load_module
  File "/home/mkassner/pupil/deploy_player/build/bundle/out00-PYZ.pyz/video_capture", line 23, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-2.1.1dev_67610f2_mod-py2.7.egg/PyInstaller/loader/pyi_importers.py", line 420, in load_module
ImportError: /opt/pupil_player/cv2.so: undefined symbol: _ZN2cv11arrowedLineERNS_3MatENS_6Point_IiEES3_RKNS_7Scalar_IdEEiiid

It's not trying to access libschroedinger anymore though :)

**Comment by mkassner** [comment] 2015-10-02 07:02
Ok, this must be a problem with the way opencv is compiled. I m pretty sure they are using `rpath` during linking and that can cause problems. I have test machines (Ubuntu) with OpenCV installed and without and I never get this. It must be a environment setup that is causing this.

**Comment by mkassner** [comment] 2015-10-02 07:41
Hi,  I tried something else. Could you try installing and running the latest Pupil Capture bundle (113) from here: https://github.com/pupil-labs/pupil/releases/tag/v0.6.10 ?

**Comment by Sijben** [comment] 2015-10-02 08:06
It works! This capture runs without any errors. (What was changed?)

**Comment by mkassner** [comment] 2015-10-02 08:15
Great! OpenCv needs to be compiled with the explicit directive to not use rpaths. I just updated Pupil Player, you can use that too then. I ll close this issue.

**Closed by mkassner** 2015-10-02 08:15 UTC
