### ISSUE TITLE
Windows Bundle stability

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil#113] opened 2015-03-15 11:14 UTC
I have been burn-in testing the windows bundle and with my setup (single usb pupil with surface pro) and the world process sometimes freezes. The window does not react, no screen update. I m guessing its hanging in some blocking call to pyvideoinput.

I don't see any errors on the log files.

We need:
 * pyvideoimput to log any errors
 * pyvideoimput to recover from capture errors by restarting the capture.

If these crashes are related to pyvideoimput this should help us to fix it.

**Comment by mkassner** [comment] 2015-03-17 10:19
This would be really useful. Any updates?

**Comment by MichaelBarz** [comment] 2015-04-16 16:10
experienced following error on bundle start:
division by zero (world.py, line 303)

Probably due to delays on loading capture device...

**Comment by MichaelBarz** [comment] 2015-04-21 15:25
* [ ] automatically restart capture on error (fall back to working setting)

**Comment by WillemVlakveld** [comment] 2015-05-05 05:09
I have tested the third test bundle of Pupil Capture for Windows on three different computers (one with Intel i7 and two with Intel i5 and all with 8 Gb). One had Windows 7 installed and two had Windows 8.1 installed. The eye tracker I have used was the ‘Pupil Dev’. 
On all three computers I had to install the drivers of the Logitech webcam C525 and the Microsoft Lifecam 5000 first. After having installed these drivers, Pupil Capture ran stable on all three computers. 
The only thing is that before closing Pupil Capture I had to reset window size of both ‘Eye’ and ‘World’ first. When I didn’t reset window size before shutting off Pupil Capture, the next time I started Pupil Capture only the ‘World’ appeared and ‘Eye’ didn’t appear.

**Comment by MichaelBarz** [comment] 2015-05-06 18:03
Thanks for your comment. I'll test this scenario...

**Comment by cpicanco** [comment] 2015-05-06 18:23
Something like this occurred to me. Only the Eye window appeared though. Closing the app and deleting the configs persistence folder was enough to recover the initial state.

**Comment by MichaelBarz** [comment] 2015-05-14 13:43
Hi, I cannot reproduce the issue anymore. But I did some changes since the third bundle was released. Especially the commit 72d753f might influence the behavior regarding this issue. 
So, watch out for the fourth test bundle...

**Closed** 2015-05-18 11:53 UTC
Labels: Bundle, Windows
