### ISSUE TITLE
OSerror and crash of Pupil Capture at end of calibration, Windows 10

### ISSUE THREAD

**Issue by d-arzounian** [pupil-labs/pupil#1733] opened 2019-11-14 11:04 UTC
I run calibration in Pupil Capture and after all markers have been displayed the world video freezes.  Pupil reports the following error:

`OSError: Failed to open file b'C:\\Users\\Doroth\xc3\xa9e\\AppData\\Local\\Temp\\scipy-7i51g6sx'`

I checked the hard drive and there is no such directory as C:\\Users\\Doroth\xc3\xa9e\. However I could find the scipy-7i51g6sx file in C:\\Users\\Dorothée\\AppData\\Local\\Temp\\
Is Pupil misinterpreting my user name? How can this be solved ?

**Comment by papr** [comment] 2019-11-14 11:27
Hey, yes, that is exactly what is happening. Please create a separate user account that does not include any non-ascii characters.

**Comment by papr** [comment] 2019-11-14 12:14
Related to https://github.com/pupil-labs/pupil/issues/1635

**Comment by d-arzounian** [comment] 2019-11-14 12:37
I see, thank you. I will create a separate user account dedicated to using Pupil softwares. However that is going to be quite inconvenient. It would be great if this could be avoided in the future.
Also it is curious, I had used Pupil for a while on this account before and never had the issue until today.

**Comment by papr** [comment] 2019-11-14 12:55
I am very sorry for the inconvenience. There are a few issues related to unicode paths on Windows which need to be investigated. It is indeed weird that this error has not appeared before. Could you share the capture.log file after the application having crashed. It contains more information about the error and helps us to reproduce the issue.

**Comment by d-arzounian** [comment] 2019-11-14 13:34
Here is one such log file attached.
[capture.log](https://github.com/pupil-labs/pupil/files/3846698/capture.log)

**Comment by papr** [comment] 2019-11-14 16:22
Which version have you used before that did not throw this error?
> Traceback (most recent call last):
  File "launchables\world.py", line 626, in world
  File "shared_modules\accuracy_visualizer.py", line 187, in on_notify
  File "shared_modules\accuracy_visualizer.py", line 217, in recalculate
  File "qhull.pyx", line 2420, in scipy.spatial.qhull.ConvexHull.__init__
  File "qhull.pyx", line 269, in scipy.spatial.qhull._Qhull.__init__
  File "messagestream.pyx", line 36, in scipy._lib.messagestream.MessageStream.__init__
OSError: Failed to open file b'C:\\Users\\Doroth\xc3\xa9e\\AppData\\Local\\Temp\\scipy-2idlg_gz'

This is the full error. Unfortunately, this seems to be a scipy internal error. See https://github.com/scikit-image/scikit-image/issues/3277 which has not been fixed yet. I have asked to reopen the issue.

**Comment by papr** [comment] 2019-11-14 16:22
@d-arzounian You can disable the accuracy visualizer plugin until the issue has been fixed.

**Comment by d-arzounian** [comment] 2019-11-14 16:33
Disabling the accuracy visualizer plugin did stop the problem, thank you!

I had used v1.16 successfully, then I started getting the error with that version and updating to v1.18 did not fix it.

**Comment by papr** [comment] 2019-11-16 14:13
Reference scipy issue: https://github.com/scipy/scipy/issues/8850

> The problem may happens when non-English characters (in my case, Chinese) are included in your TEMP directory e.g. C : /users/%%your username%%/......./TEMP . Normally, these characters are used to define your username, and they will be encoded in messagestream.pyx to open an autogenerated temporary file. As the way of encoding may not be compatible with your language, the encoded filename (dirs included) will mislead the "sdio.fopen" function following behind and bring errors.

> Solution: Change the directories in the environment variables TEMP and TMP to some directories that doesn't contain non-English characters

I will close this issue since it not directly related to Pupil. I am subscribed to the actual scipy issue and will update the bundled scipy as soon as it has been fixed.

**Closed by papr** 2019-11-16 14:13 UTC
Labels: Windows, bug
