### ISSUE TITLE
Pupil Player executable arguments

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#810] opened 2017-08-21 21:13 UTC
Hi, I was trying to run pupil player (0.13) by command line, as usual:

> pupil_player /some/old/pupil/recording/path/

No success. Player will open in the "drag drop" state. Am I missing something?

**Comment by fneitzel** [comment] 2017-08-22 08:44
Same here. Drag and Drop on the pupil player icon doesn't work as well.

**Comment by mkassner** [comment] 2017-08-22 09:57
Thanks for the report. We are working on resolving this. In the meantime please drag onto the window. That still works.

**Comment by cpicanco** [comment] 2017-08-22 11:15
Unfortunately the drag and drop functionality stopped work a long time ago (Open Box desktop and Thunar file manager). Regardless of, Will Patera reproduced the bug.

**Comment by mkassner** [comment] 2017-08-22 11:27
@cpicanco  this is not the case for standard ubuntu. Running from source still works so I must investigate the bootloader.

**Comment by cpicanco** [comment] 2017-08-22 12:41
Hi @mkassner , drag and drop depends on what on ubuntu? Should I look into glfw stuff?

**Comment by cpicanco** [comment] 2017-08-22 12:52
I guess I have found the issue on my system. Not related to Open Box. It is related to Thunar and its XFCE https://github.com/glfw/glfw/issues/968

**Comment by willpatera** [comment] 2017-10-27 10:50
@cpicanco @fneitzel I can confirm that if you are running from source you can provide the path as an argument and it works just fine. However, we need to investigate this when we are making the next app bundle.

**Comment by papr** [comment] 2017-10-31 16:30
1. `pupil_player /some/old/pupil/recording/path/` should be fixed with https://github.com/pupil-labs/pupil/pull/761/files#diff-da1129ccc15ee6efbc933f18d621524bL233
2. Dragging onto the icon on macOS does not work: This seems to be an symptom of https://github.com/pyinstaller/pyinstaller/issues/1309 I can confirm that this is not an issue of wrong `Info.plist` keys.

**Comment by papr** [comment] 2017-11-09 10:26
We will move this issue to the v1.2 since this seems to be an issue with `pyinstaller` and is not easily resolvable.

**Comment by papr** [comment] 2017-11-20 09:06
**Version:** `v1.1`
**Problem:** Running `pupil_player <recording>` does not open the recording but shows the drag&drop window instead.
**Work-around:** Run `pupil_player workaround <recording>` instead.
**Long-term solution:** Use `argparse` to identify correct arguments

**Closed** 2018-01-09 16:16 UTC
