### ISSUE TITLE
Caching for Fixation Detector

### ISSUE THREAD

**Issue by marc-tonsen** [pupil-labs/pupil#1336] opened 2018-10-19 15:13 UTC
Computing fixations for a recording can take a long time. Similar to how the surface tracker caches square markers and saves them to file, the fixation detector should also save his results and reload them after a restart of the software.

**Comment by papr** [comment] 2018-10-19 15:27
This is a duplicate of at least two other open issues :-)

**Closed by papr** 2018-10-19 15:28 UTC
Labels: enhancement
