### ISSUE TITLE
Pupil Capture 2.0 crashes on macOS Mojave 10.14.6

### ISSUE THREAD

**Issue by siyakunde** [pupil-labs/pupil#1970] opened 2020-07-14 22:44 UTC
I downloaded the latest version of the Pupil Capture app (pupil_v2.0-182-gf9db20b1_macos_x64.dmg) and installed it. Connected my Pupil Core device to the laptop and double clicked on Pupil Capture icon in Applications. The app does not open. Right click on dock icon shows that it's "Not Responding" always. This is a persistent issue, not sporadic.

**I used the following command in terminal:** tail -f /var/log/system.log

**I get the following error:** com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.pupil_capture.65418): Could not resolve origin of domain. XPC services in this domain's bundle will not be bootstrapped: error = 107: Malformed bundle, taint = missing executable

**Following is the content of capture.log:**
2020-07-14 17:40:35,239 - MainProcess - [INFO] os_utils: Disabled idle sleep.
2020-07-14 17:40:36,344 - world - [INFO] numexpr.utils: NumExpr defaulting to 4 threads.
2020-07-14 17:40:36,797 - world - [INFO] launchables.world: Application Version: 2.0.182
2020-07-14 17:40:36,797 - world - [INFO] launchables.world: System Info: User: skunde, Platform: Darwin, Machine: cse-bduncan-18.unl.edu, Release: 18.7.0, Version: Darwin Kernel Version 18.7.0: Mon Apr 27 20:09:39 PDT 2020; root:xnu-4903.278.35~1/RELEASE_X86_64
2020-07-14 17:40:36,797 - world - [DEBUG] launchables.world: Debug flag: False
2020-07-14 17:40:40,673 - world - [DEBUG] video_capture.ndsi_backend: Suppressing pyre debug logs (except zbeacon)
2020-07-14 17:40:40,941 - world - [DEBUG] remote_recorder: Suppressing pyre debug logs (except zbeacon)
2020-07-14 17:40:40,982 - world - [DEBUG] pupil_apriltags: Testing possible hit: /Applications/Pupil Capture.app/Contents/MacOS/pupil_apriltags/lib/libapriltag.3.dylib...
2020-07-14 17:40:41,007 - world - [DEBUG] pupil_apriltags: Found working clib at /Applications/Pupil Capture.app/Contents/MacOS/pupil_apriltags/lib/libapriltag.3.dylib
2020-07-14 17:40:41,052 - world - [DEBUG] file_methods: Session settings file '/Users/skunde/pupil_capture_settings/user_settings_world' not found. Will make new one on exit.
2020-07-14 17:40:41,052 - world - [INFO] launchables.world: Session setting are from a different version of this app. I will not use those.
2020-07-14 17:40:41,314 - world - [DEBUG] plugin: Plugin HMD_Streaming_Manager failed to load, not available for import.
2020-07-14 17:40:41,314 - world - [DEBUG] plugin: Plugin Dummy_Gaze_Mapper failed to load, not available for import.
2020-07-14 17:40:41,314 - world - [DEBUG] plugin: Loading plugin: UVC_Manager with settings {}
2020-07-14 17:40:41,322 - world - [DEBUG] plugin: Loading plugin: NDSI_Manager with settings {}
2020-07-14 17:40:41,322 - world - [DEBUG] ndsi.network: Starting network...
2020-07-14 17:40:56,328 - MainProcess - [INFO] os_utils: Re-enabled idle sleep.

**Comment by papr** [comment] 2020-07-14 22:45
Closing as this is a duplicate of #1919

**Closed** 2020-07-14 22:45 UTC

**Comment by papr** [comment] 2020-07-16 08:26
The fix has been released as part of the [v2.1 release](https://github.com/pupil-labs/pupil/releases/v2.1).

**Comment by siyakunde** [comment] 2020-07-16 18:53
Hi,

Thank you for getting back to me. I will try this.

Thanks & Regards,
Siya Kunde
