### ISSUE TITLE
Pupil Capture Eye crashes

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#210] opened 2015-10-04 04:23 UTC
In pupil_capture master (7bde208098df16ed7484129a42a700b34f175835) and in the last bundle (140ec81), eye process will crash after some seconds:

> EYE0 Process [WARNING] uvc : Could not grab frame. Restarting device
> EYE0 Process [ERROR] eye : Capture from Camera Failed. Stopping.

Using Logitech C615 and Microsoft HD-5000. 

For some reason, the eye camera was being shown as `unknown`. I was used to see Microsoft Lifecam HD-5000 in the dropbox.

**Comment by cpicanco** [comment] 2015-10-04 04:38
```
Estimated / selected altsetting bandwith : 732 / 800. 
Estimated / selected altsetting bandwith : 309 / 512. 
EYE0 Process [WARNING] uvc : Could not grab frame. Restarting device
EYE0 Process [ERROR] uvc : Can't stop stream: Error:'Operation timed out.'. Will ignore this and try to continue.
Estimated / selected altsetting bandwith : 309 / 512. 
EYE0 Process [WARNING] uvc : Could not grab frame. Restarting device
EYE0 Process [ERROR] uvc : Can't stop stream: Error:'Operation timed out.'. Will ignore this and try to continue.
Estimated / selected altsetting bandwith : 309 / 512. 
EYE0 Process [WARNING] uvc : Could not grab frame. Restarting device
EYE0 Process [ERROR] eye : Capture from Camera Failed. Stopping.
```

**Comment by mkassner** [comment] 2015-10-04 06:59
Hi, whats the last working commit?

**Comment by mkassner** [comment] 2015-10-04 06:59
I cant reproduce this with the normal pupil dev/pro cameras.

**Comment by cpicanco** [comment] 2015-10-04 16:31
> Hi, whats the last working commit?

I was not taking notes. Both cameras were fully working long time ago before libuvc. Eye camera was working just fine until recently in 5.x.  For pupil I could just do a git checkout and test, but is there an easy way to alternate from a dependency version to another (pyglui, uvc, pyav)?

**Comment by mkassner** [comment] 2015-10-04 19:52
So this error was introduced with pyuvc?

I think in your particular case replacing the pyuvc backend with the older pyv4l2 version and make a few changes to bring the api up to speed could be a good option. Its hard for us to debug since we dont have the same cameras :-(

**Comment by cpicanco** [comment] 2015-10-04 20:10
No, this error was not introduced with pyuvc. The following error was introduced with pyuvc: (https://github.com/pupil-labs/pyuvc/issues/3).

Perhaps this error was introduced somewhere between 5x and 6x. I am not sure. Fell free to put a "will not fix" tag, I understand the circumstances.

Right now I am using the capture from april 15 and the most recent player with a little trick. After checkout the required stuff back, pyv4l2 is giving an strange error (could not set format). But this error occurs only sometimes. Closing and opening, closing and opening will eventually make the error stop. Since it works sometimes, I am guessing it is a pyv4l2 issue.

**Comment by cpicanco** [comment] 2015-10-04 20:17
Just to make it clear... The reported issue was verified in the master and in the bundle. The April 15 capture I am using is another thing. May I ask if is it possible to install two pyglui versions in the same machine?? If yes how??

**Comment by cpicanco** [comment] 2015-10-05 00:49
Hi. I did something that fixed the problem (don't know what).

- Reinstall pyglui;
- Bandwidth patch was Applied; 
- ...

```
EYE0 Process [ERROR] video_capture : No accessible device found that matched ['Pupil Cam1 ID0', 'HD-6000', 'Integrated Camera', 'HD USB Camera', 'USB 2.0 Camera']
EYE0 Process [WARNING] video_capture : Starting with Fake_Capture.
Estimated / selected altsetting bandwith : 732 / 800. 
Estimated / selected altsetting bandwith : 309 / 512. 
Estimated / selected altsetting bandwith : 904 / 944. 
EYE0 Process [ERROR] uvc : Can't stop stream: Error:'Operation timed out.'. Will ignore this and try to continue.
```
Somehow the message in the dropbox now shows "Microsoft".

Also, the same uvc problem as usual...

```
WORLD Process [ERROR] uvc : Could not init 'Auto Exposure Mode'!
WORLD Process [ERROR] uvc : Could not init 'Auto Exposure Priority'!
WORLD Process [ERROR] uvc : Could not init 'Absolute Exposure Time'!
WORLD Process [ERROR] uvc : Could not init 'Auto Focus'!
WORLD Process [ERROR] uvc : Could not init 'Absolute Focus'!
WORLD Process [ERROR] uvc : Could not init 'Zoom absolute control'!
WORLD Process [ERROR] uvc : Could not init 'Pan control'!
WORLD Process [ERROR] uvc : Could not init 'Tilt control'!
WORLD Process [ERROR] uvc : Could not init 'Backlight Compensation'!
WORLD Process [ERROR] uvc : Could not init 'Brightness'!
WORLD Process [ERROR] uvc : Could not init 'Contrast'!
WORLD Process [ERROR] uvc : Could not init 'Gain'!
WORLD Process [ERROR] uvc : Could not init 'Power Line frequency'!
WORLD Process [ERROR] uvc : Could not init 'Saturation'!
WORLD Process [ERROR] uvc : Could not init 'Sharpness'!
WORLD Process [ERROR] uvc : Could not init 'White Balance temperature'!
WORLD Process [ERROR] uvc : Could not init 'White Balance temperature,Auto'!
```

**Comment by cpicanco** [comment] 2015-10-05 00:56
![screenshot from 2015-10-04 21 54 54](https://cloud.githubusercontent.com/assets/6511849/10271333/9d621444-6ae2-11e5-9631-913a31a84cad.png)

**Comment by mkassner** [comment] 2015-10-05 06:38
Thats great to hear. Since this error is specific to your setup I m closing the issue.

**Closed by mkassner** 2015-10-05 06:38 UTC

**Comment by cpicanco** [comment] 2015-10-08 09:23
Today Pupil is not in the mood.
```
EYE0 Process [ERROR] eye : Capture from Camera Failed. Stopping.
Failed to connect to Speech Dispatcher:
Error: Can't connect to unix socket /run/user/1000/speech-dispatcher/speechd.sock: No such file or directory. Autospawn: Autospawn failed. Speech Dispatcher refused to start with error code, stating this as a reason: Speech Dispatcher already running.
```

**Comment by cpicanco** [comment] 2015-10-08 09:24
The camera starts good. Stays a little longer than this.

**Comment by cpicanco** [comment] 2015-10-08 09:28
Could it be a Ubuntu related issue?? Yesterday or so kernel was updated.

**Comment by PRNV7** [comment] 2017-02-16 14:43
@cpicanco What is your kernel version and pyuvc version you've used?

**Comment by cpicanco** [comment] 2017-02-16 16:36
@PRNV7. This issue is old. Also, it is confusing because many different problems were reported. May I ask why revisite it?

- All "Could not init" errors were related to pyuvc (or libuvc) and noe are solved.

- "Speech dispacher" error was related to Audio requests being made on a system without "speech" dependencies.

- The "opening and closing"  (trial and error) method was a workaroud to set camera bandwidths that system would like. Pupil now have a much better control on camera bandwidth. Hence, "Could not grab frame" errors should not occur in supported usb controllers.

**Comment by PRNV7** [comment] 2017-02-16 18:11
@cpicanco  Thanks. Because I'm got errors even when I ran the pyuvc example.py on Odroid based on Ubuntu with kernel version 3.10 but it works fine in my ubuntu16(kernel 4.4, mainline) so I thought kernel update might count.
