### ISSUE TITLE
Windows Setup

### ISSUE THREAD

**Issue by infermachine** [pupil-labs/pupil#540] opened 2016-12-06 01:13 UTC
It looks like there is no windows executable, so I am currently installing all the dependencies required to get Pupil Capture running on Windows 10 (64 bit, x64). I think I have it all set up according to the instruction page, but when I try to open Capture with "python main.py" (using python 2.7.6) and I get the following output:

`C:\Users\Umake\Documents\pupil_src\capture>python main.py
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
Process world:
Traceback (most recent call last):
  File "C:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Umake\Documents\pupil\pupil_src\capture\world.py", line 75, in world
    assert pyglui_version >= '1.0'
AssertionError`

I tried to solve the pylgui issues by installing a newer version (I think 0.8 is currently installed), but after running the "python setup.py install" I get the following output:

`
C:\Users\Umake\Documents\PupilDependencies\pyglui>python setup.py install
C:\Python27\lib\site-packages\Cython\Distutils\old_build_ext.py:30: UserWarning: Cython.Distutils.old_build_ext does not properly handle dependencies and is deprecated.
  "Cython.Distutils.old_build_ext does not properly handle dependencies "
'glew.pxd' is up-to-date.
pyglui/ui.pyx: cannot find cimported module 'pyglui.cygl'
pyglui/graph.pyx: cannot find cimported module 'pyglui.cygl'
running install
running bdist_egg
running egg_info
writing pyglui.egg-info\PKG-INFO
writing top-level names to pyglui.egg-info\top_level.txt
writing dependency_links to pyglui.egg-info\dependency_links.txt
reading manifest file 'pyglui.egg-info\SOURCES.txt'
writing manifest file 'pyglui.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
running build_ext
building 'pyglui.ui' extension
C:\Users\Umake\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ipyglui/cygl/ -Ipyglui/cygl/win_glew -Ipyglui/pyfontstash/fontstash/src -IC:\Python27\include -IC:\Python27\PC /Tppyglui/ui.cpp /Fobuild\temp.win32-2.7\Release\pyglui/ui.obj -O2
ui.cpp
pyglui/ui.cpp(441) : fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory
error: command '"C:\Users\Umake\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe"' failed with exit status 2
`

I come from Unix and the python setup.py install seems like a unix command, but I don't know if something else needs to be run with windows? I think I have a stdint.h in my Visual studio path (...\include.stdint.h) but maybe it's not the right one or it's set up incorrectly?

If anyone has any ideas, I'm all ears! Thanks!

**Comment by willpatera** [comment] 2016-12-06 03:45
Hi @infermachine - we are currently working on getting Pupil Capture, Pupil Player, and Pupil Service up and running on Windows 10 (64bit) using Python 3.5 and Opencv 3.0 and hope to release a bundle for Windows 10 very soon (hopefully within the next week). 

Also, once we get everything up and running we will update the development instructions so that others can also build from source.

**Comment by mkassner** [comment] 2016-12-08 20:43
I closed this because the fix for the problem is coming soon but not directly related to the issue.

**Comment by matiarj** [comment] 2017-08-30 01:15
currently running into this problem

**Comment by matiarj** [comment] 2017-08-30 01:15
C:\work\pupil\pupil_src\shared_modules\pupil_detectors>python setup.py build
running build
running build_ext
building 'pupil_detectors.detector_2d' extension
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I. -IC:\Python36\lib\site-packages\numpy\core\include -IC:\work\opencv\build\include -IC:\work\Eigen -IC:\work\ceres-windows\ceres-solver\include -IC:\work\ceres-windows\glog\src\windows -IC:\work\ceres-windows -IC:\work\boost\stage\lib -I../../shared_cpp/include -Isingleeyefitter/ -IC:\Python36\include -IC:\Python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\winrt" "-IC:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\VC\Tools\MSVC\14.11.25503\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\VC\Tools\MSVC\14.11.25503\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\winrt" /EHsc /Tpdetector_2d.cpp /Fobuild\temp.win-amd64-3.6\Release\detector_2d.obj -D_USE_MATH_DEFINES -std=c++11 -w -O2
cl : Command line warning D9025 : overriding '/W3' with '/w'
cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
detector_2d.cpp
c:\work\pupil\pupil_src\shared_modules\pupil_detectors\singleeyefitter/fun.h(9): fatal error C1083: Cannot open include file: 'boost/iterator_adaptors.hpp': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

**Comment by willpatera** [comment] 2017-08-30 07:01
@matiarj This looks like it is related to Boost. Could you make sure that the directions for boost install are followed here: https://docs.pupil-labs.com/#boost

**Comment by matiarj** [comment] 2017-08-30 14:15
I followed those instructions multiple times. How many files are there
supposed to be in work/boost/stage/lib?

-- 
Matiar Jafari

**Closed** 2017-11-02 08:35 UTC
Labels: Windows

**Comment by iserranoe** [comment] 2018-04-06 12:51
@matiarj:  Where you able to solve the problem?

**Comment by matiarj** [comment] 2018-04-06 17:46
No however I haven't tried in a while.

-- 
Matiar Jafari
