### ISSUE TITLE
Provide support for linux desktops other than unity

### ISSUE THREAD

**Issue by brittAnderson** [pupil-labs/pupil#940] opened 2017-11-17 14:30 UTC
feature request

Per #936 puil capture does work on Xubuntu, but pupil_player does **not**. It would be nice if the missing components could be identified (possibly related to the gui) so that pupil apps would run on linux systems using lighter weight desktop environments. Alot of my hardware is older, and things run much more nimbly when I can use something like xfce.

**Comment by cpicanco** [comment] 2017-11-17 15:00
Yes, it is possible (for advanced users) to identify, but pupil devs will not be able to maintain such a diverse set of distros. May I ask if you would be happy with Arch Linux? @willpatera have been testing pupil against Arch Linux. Is there anything lighter than Arch Linux?

**Comment by willpatera** [comment] 2017-11-17 15:09
@cpicanco Pupil works well on Arch (Antergos) in my experience. But, in my opinion, Arch is for for more advanced users compared to Ubuntu.  

@brittAnderson if you launch `pupil_player` via terminal and share the stack trace and `player.log` we might be able to identify issues.

**Comment by brittAnderson** [comment] 2017-11-17 16:34
The only terminal output is also the only entry in the log file:

`2017-11-17 11:11:33,941 - MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.`

**Comment by hitmuri** [comment] 2017-11-18 09:38
Hi all,

On Debian testing, pupil_player works fine with the MATE desktop but not with Xfce. I get the same log line in both though.

**Comment by papr** [comment] 2017-11-20 08:55
@hitmuri @brittAnderson 
Please run `pupil_capture`, `pupil_player debug`, or `pupil_player debug <recording path>` on Xfce and share the terminal output with us.

**Comment by hitmuri** [comment] 2017-11-20 09:05
This is the output of pupil_player debug : 
`Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
 `

`pupil_player debug recording_folder` works fine, it opens the recording contrary to `pupil_player recording_folder`

the output is this : 
`Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS ver
sion.
player - [INFO] launchables.player: Starting new session with '/home/flo/INFO/Pr
ojets/Boeuf/experiments/expecom/recordings/2017_11_15/000'
player - [INFO] player_methods: Updating meta info
player - [INFO] video_capture: Install pyrealsense to use the Intel RealSense ba
ckend
player - [INFO] launchables.player: Application Version: 1.1.2
player - [INFO] launchables.player: System Info: User: flo, Platform: Linux, Mac
hine: hitlap, Release: 4.9.0-2-amd64, Version: #1 SMP Debian 4.9.18-1 (2017-03-3
0)
player - [INFO] camera_models: Previously recorded calibration found and loaded!
player - [INFO] launchables.player: Process shutting down.`

**Comment by brittAnderson** [comment] 2017-11-20 14:04
My outputs are very similar:

```

britt@zurich:/opt/pupil_player$ ./pupil_player debug
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
britt@zurich:/opt/pupil_player$ ./pupil_player debug /home/britt/recordings/2017_11_16/001/
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
player - [INFO] launchables.player: Starting new session with '/home/britt/recordings/2017_11_16/001/'
player - [INFO] player_methods: Updating meta info
player - [INFO] video_capture: Install pyrealsense to use the Intel RealSense backend
player - [INFO] launchables.player: Application Version: 1.1.2
player - [INFO] launchables.player: System Info: User: britt, Platform: Linux, Machine: zurich, Release: 4.10.0-38-generic, Version: #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017
player - [INFO] camera_models: Previously recorded calibration found and loaded!
player - [WARNING] vis_eye_video_overlay: Video for eye0 was not found or could not be opened.
player - [INFO] camera_models: No user calibration found for camera eye1 at resolution (640, 480)
player - [INFO] camera_models: No pre-recorded calibration available
player - [WARNING] camera_models: Loading dummy calibration
player - [WARNING] launchables.player: Previous export for range [0-1121] already exsits - overwriting.
player - [WARNING] video_export_launcher: Adding new video export process.
player - [WARNING] video_export_launcher: Added export
player - [INFO] fixation_detector: Created 'fixations.csv' file.
player - [INFO] fixation_detector: Created 'fixation_report.csv' file.
Starting video export with pid: 2653
Process Export (pid: 2653) crashed with trace:
Traceback (most recent call last):
  File "shared_modules/exporter.py", line 185, in export
  File "shared_modules/fixation_detector.py", line 377, in recent_events
AttributeError: 'Offline_Fixation_Detector' object has no attribute 'current_fixation_details'

player - [INFO] launchables.player: Process shutting down.

```

**Comment by papr** [comment] 2017-11-20 14:49
It looks like the issue was not caused by Xfce but with #810 and #950. These issues will be fixed in the upcoming version.

**Closed by papr** 2017-11-20 14:49 UTC
Labels: Linux
