### ISSUE TITLE
World/Main Window Crash on Surface-Tracking (Windows)

### ISSUE THREAD

**Issue by Aeefire** [pupil-labs/pupil#631] opened 2017-02-17 08:51 UTC
Hey,

I just added a surface with two markers (+ edited the surface) and after some seconds the main-window crashes (eye windows are still available and tracking the pupil).

Any ideas? I can gladly provide you with more details, if needed.

**Hardware used**
Pupil Labs Binocular Eye Tracker, 120 Hz

**Software used**
Pupil Capture for Windows, v0.8.7-w-20 (packaged)

**Error message**
`OpenCV Error: Assertion failed (depth == CV_32F || depth == CV_64F) in cv::perspectiveTransform, file D:\Build\OpenCV\opencv-3.1.0\modules\core\src\matmul.cpp, line 2126
Process world:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 249, in _bootstrap
  File "multiprocessing\process.py", line 93, in run
  File "world.py", line 478, in world
  File "surface_tracker.py", line 207, in update
  File "reference_surface.py", line 412, in map_data_to_surface
  File "reference_surface.py", line 412, in <listcomp>
  File "reference_surface.py", line 406, in map_datum_to_surface
cv2.error: D:\Build\OpenCV\opencv-3.1.0\modules\core\src\matmul.cpp:2126: error: (-215) depth == CV_32F || depth == CV_64F in function cv::perspectiveTransform
`

**Comment by papr** [comment] 2017-02-17 08:54
Dear @Aeefire 
This is a duplicate of #598 and has already been fixed.
The fix will be part of the next release.

**Closed by papr** 2017-02-17 08:54 UTC
