### ISSUE TITLE
Windows Bundle: Accuracy test not working 

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/pupil#122] opened 2015-03-19 10:23 UTC
user report: Accuracy Test not working for me. If I put (after I have done the screen marker calibration) the calibration method to accuracy test and click on Error Calculation nothing happens. If I click on the “C” Button the program crashes down. An Accuracy Test Window is opening but is not answering. 

Needs to be confirmed and fixed. This issue might now be windows specific.

**Comment by mkassner** [comment] 2015-03-20 07:42
I can reproduce this error. Its a bug in the plugin. Its needs to be updated anyways.

**Comment by willpatera** [comment] 2015-04-10 08:41
I made some updates/fixes to `accuracy_test` at this commit https://github.com/pupil-labs/pupil/commit/7b4d317db428b5031acabe0a0cdda0f1a17c94a2 -- now it runs without crashing world, but the update needs to be completed.

Todo:
  - [ ] Update marker rendering following `screen_marker_calibration.py`
  - [ ] Make controls for speed and marker size following `screen_marker_calibration.py`

**Comment by MichaelBarz** [comment] 2015-04-17 13:45
Could not reproduce this issue anymore. Might have been fixed with previous change.

I'm not sure, but marker rendering is not due to windows?! I'll open another issue https://github.com/pupil-labs/pupil/issues/132 for these todos to close this one.

**Closed by MichaelBarz** 2015-04-17 13:45 UTC
Labels: bug, Bundle, Windows
