### ISSUE TITLE
Pupil Player v0.9.10 - Downwards Compatibility?

### ISSUE THREAD

**Issue by fneitzel** [pupil-labs/pupil#650] opened 2017-03-01 11:53 UTC
I tried to export an older recording:

**CONSOLE LOG:**
$ pupil_player '/home/testing/recordings/2017_02_11/163' 
Player [INFO] player_methods : Updating meta info
Player [INFO] __main__ : Application Version: 0.9.1.10
Player [INFO] __main__ : System Info: User: testing, Platform: Linux, Machine: vermeer, Release: 4.4.0-34-generic, Version: #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016
Traceback (most recent call last):
  File "main.py", line 626, in <module>
  File "main.py", line 241, in session
KeyError: 'pupil_positions'
Failed to execute script main

**info.csv**

    key,value
    Recording Name,2017_02_11
    Start Date,11.02.2017
    Start Time,12:20:27
    System Info,"User: testing, Platform: Linux, Machine: vermeer, Release: 4.4.0-34-generic, Version: #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016"
    World Camera Frames,70306
    World Camera Resolution,1280x720
    Duration Time,00:39:23
    Capture Software Version,0.8.7
    Data Format Version,v0.9.1

**Comment by cpicanco** [comment] 2017-03-01 12:28
duplicate of #634

**Comment by cpicanco** [comment] 2017-03-01 12:29
@fneitzel , please, if possible, attach the recording without the videos here, as @mkassner asked.

**Comment by mkassner** [comment] 2017-03-01 12:47
@fneitzel  or send it to us via email/cloudshare etc...

**Comment by mkassner** [comment] 2017-03-01 16:24
using the data provided by @fneitzel  I fixed the issue. The latest version is master has this commit. 

We will release a bundle in a bit!

Please edit your info.csv file and remove the data_format line. This will trigger a conversion.

**Closed by mkassner** 2017-03-01 16:24 UTC
