### ISSUE TITLE
Corrupted files after closing eye window during recording

### ISSUE THREAD

**Issue by uncflorians** [pupil-labs/pupil#470] opened 2016-09-21 02:19 UTC
By mistake, I closed the eye window during a recording session and I found my recorded files being corrupted afterwards. That means, I cannot open them in the pupil player.
Is there a way to repair/manipulate the data files before importing them into pupil player?

Thanks!

**Comment by mkassner** [comment] 2016-09-21 08:41
did you record the eye video as well?

**Comment by uncflorians** [comment] 2016-09-21 13:30
Yes

**Comment by mkassner** [comment] 2016-09-23 13:17
In that case can you remove the eye videos and try?

**Comment by uncflorians** [comment] 2016-09-23 13:20
I already tried that, without success.

**Comment by mkassner** [comment] 2016-09-23 13:32
can you upload the recording and share if with us?

**Comment by uncflorians** [comment] 2016-09-23 15:11
The complete recording is 35 GB. Would it be enough to upload all files except the videos?

**Comment by mkassner** [comment] 2016-09-27 07:46
I think that sound suffice.

**Comment by uncflorians** [comment] 2016-09-27 15:59
Okay, the file is still to big for uploading in github (max is 10 MB). I zipped it and load it into dropbox: https://www.dropbox.com/s/i0xxoaaxpteo7pz/000.zip?dl=0

Hope you can find something in the files.

**Comment by mkassner** [comment] 2016-09-29 10:22
We inserted a world.mp4 file into your recording and opened it with a recent version of pupil player (v0.8.4 and v0.8.5). While it did take a bit to load (1min on an old mac laptop), we could not reproduce your error.

Please make sure that work eye video file and timestamps file is removed. Also make sure that player does not have the eye video overlay plugin loaded.

**Comment by mkassner** [comment] 2016-10-13 19:28
Ill close this now.

**Closed by mkassner** 2016-10-13 19:28 UTC
