### ISSUE TITLE
No Audio Capturing

### ISSUE THREAD

**Issue by pasbi** [pupil-labs/pupil#747] opened 2017-06-13 19:15 UTC
I use the Logitech high-resolution camera, which is correctly recognized by e.g. VLC player (audio and video).
pupil_capture, also detects it as audio source, but after finishing a recording, there is no `audio.wav` and no `audio_timestamps.npy`.
`world.mp4` and `eye.mp4` (and some other files) are there as expected.

I use Ubuntu and the latest pupil release (v0.9.12).

**Comment by pasbi** [comment] 2017-06-14 06:28
Sometimes, pupil says
"world - [WARNING] audio_capture: Audio is already being recorded"
I'm not sure what that means since I closed all processes that might access the mic.

**Comment by pasbi** [comment] 2017-06-14 07:52
The same issue occurs also in version `0.9.10` and `0.9.5`, however, `0.7.6` produces world.wav but no audio timestamps.

**Comment by papr** [comment] 2017-06-15 08:36
Dear @pasbi 
what OS do you use?

Unfortunately, I was not able to reproduce your issue on Ubuntu 16.04. But we are currently in the process of changing the audio recording procedure. Please give the following branch a try:
https://github.com/papr/pupil/tree/avsync

**Comment by pasbi** [comment] 2017-06-15 23:10
I use ubuntu 14.04 LTS.

Can I run this version with python2? I get the error `ImportError: cannot import name set_start_method`.
Google tells me to use python3 instead, however after several hours of installing dependencies and no end in sight, I wonder if there might not be a python2 solution?

**Comment by cpicanco** [comment] 2017-06-15 23:50
You will need to jnstall python3, recent pupil branches are not backward
(python 2) compatible.

**Comment by pasbi** [comment] 2017-06-16 15:43
I compiled and installed most recent OpenCV release from source (package version did not work).
When i start pupil_capture, it compiles the extension modules, but then the following error raises:
```
Process world:
Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/eyetrackinglab/pupil/pupil_src/capture/world.py", line 94, in world
    import pupil_detectors
  File "/home/eyetrackinglab/pupil/pupil_src/capture/pupil_detectors/__init__.py", line 18, in <module>
    from .detector_2d import Detector_2D
ImportError: /home/eyetrackinglab/pupil/pupil_src/capture/pupil_detectors/detector_2d.cpython-34m.so: undefined symbol: _ZN2cv9polylinesERKNS_17_InputOutputArrayERKNS_11_InputArrayEbRKNS_7Scalar_IdEEiii
```
[Downgrading Cython](https://stackoverflow.com/questions/40257850/cluster-cpython-34m-so-undefined-symbol-pyexception-check/)  or [upgrading python](https://stackoverflow.com/questions/33223713/python-ctypes-import-error-in-virtualenv) do not resolve the issue.

**Comment by pasbi** [comment] 2017-06-18 07:54
I should say that I've inspected the `detector_2d.cpython-34m.so` file and indeed it contains that symbol but it is undefined.

**Comment by papr** [comment] 2017-06-20 14:27
This is usually due to the reason that opencv is not linked correctly. Did you run `sudo ldconfig` after installing opencv?

Btw, the audio capture menu has a status text that tells you if it is recording currently. It either says `Start a new recording to save audio.` (not recording) or `Saving audio to "audio.wav".` (recording).

**Comment by pasbi** [comment] 2017-06-21 10:44
Yes I did.
I also noticed the status text, and there is no audio even after it says `Saving audio to "audio.wav"`
 :/

**Comment by pasbi** [comment] 2017-06-21 14:14
I tested pupil 0.9.12 on a fresh Ubuntu Installation:
1. Installed Ubuntu 16.04_2 LTS alongside existing Win10
2. `sudo dpkg --install pupil_{capture,player,service}_linux_os_x64_v0.9.12-2.deb`
3. plugged in pupil-headset
4. run `pupil_capture` from terminal, eye- and world-camera-image are shown live. [See what's been printed on the terminal](https://gist.github.com/anonymous/37cfeb37dea58eb12b6874e7405d6594)
5. In the `General`-section, I open the Plugin `Audio-Capture`, it says `world - [INFO] plugin: Loaded: Audio_Capture`
6. In the `Audio Capture`-section, I select the source `C930e [Logitech Webcam C930e]`, it says 
`Exception in thread Thread-9:
Traceback (most recent call last):
File "threading.py", line 916, in _bootstrap_inner
File "threading.py", line 864, in run
File "audio_capture.py", line 178, in capture_thread
File "av/container/core.pyx", line 288, in av.container.core.open (src/av/container/core.c:4987)
File "av/container/core.pyx", line 250, in av.container.core.Container.__cinit__ (src/av/container/core.c:4323)
File "av/format.pyx", line 49, in av.format.ContainerFormat.__cinit__ (src/av/format.c:1512)
ValueError: no container format 'alsa'`
7. I start the recoring: `world - [INFO] recorder: Started Recording.`
8. I stop the recording: `world - [INFO] recorder: No surface_definitions data found. You may want this if you do marker tracking.
world - [INFO] calibration_routines.camera_intrinsics_estimation: Loaded pre recorded calibration for Logitech Webcam C930e@(1280, 720).
world - [INFO] recorder: Saved Recording.`
9. I start the recording again: `world - [INFO] recorder: Started Recording.
world - [WARNING] audio_capture: Audio is already being recorded`

**Comment by papr** [comment] 2017-06-22 12:06
I can confirm that the bundle does not record audio. There are nothing about it in the logs. Work-around is to run Pupil Capture from source.

**Comment by papr** [comment] 2017-06-22 12:16
The issue will be fixed with the next bundle release. @mkassner will close the issue has soon as the new bundles are released.

**Comment by pasbi** [comment] 2017-06-28 08:57
Concerning the `ImportError: /home/eyetrackinglab/pupil/pupil_src/capture/pupil_detectors/detector_2d.cpython-34m.so: undefined symbol: _ZN2cv9polylinesERKNS_17_InputOutputArrayERKNS_11_InputArrayEbRKNS_7Scalar_IdEEiii`-Error:

We think that this is because pupil tries to access OpenCV from package _even though all packages have been uninstalled_.

What worked for me to solve this:

1. uninstall all OpenCV packages, using your package manager (e.g. `apt-get`) and `pip` (please make sure to use the correct pip version. Maybe you need e.g. `pip3.5`).
2. remove the pupil-source folder and download (or clone) it again. This is important as it is likely that pupil has built extension modules (that happens when you start it the first time). You need to rebuild them with the self-built OpenCV and getting a fresh pupil-source folder is the easiest way.
3. Download OpenCV source and build it. Make sure it finds your python3 installation.
4. start pupil from source, it should work.

**Closed** 2017-08-29 11:58 UTC
