### ISSUE TITLE
Implementing EyeRecToo methods in Pupil

### ISSUE THREAD

**Issue by tcsantini** [pupil-labs/pupil#1807] opened 2020-02-09 11:55 UTC
This issue tracks the implementation of methods from [EyeRecToo](https://atreus.informatik.uni-tuebingen.de/santini/EyeRecToo/tree/dev) in the Pupil software stack. Foreseen are four methods:

**1. The _PuRe_ pupil detector [1]**

Status: the Pupil team has already reimplemented this method in [this repository](https://github.com/pupil-labs/pfa-pupil-detector).

**2. The _PuReST_ pupil tracker [2]**

As far as I understand, Pupil doesn't differentiate pupil detectors (i.e., single frames) from pupil trackers (i.e., multiple frames). I guess this should be added as a pupil detector then?

Status: not started yet.

**3. _CalibMe_ calibration [3]**

Status: The single marker calibration is already a CalibMe calibration (see
https://github.com/pupil-labs/pupil-docs/pull/166). It however does not include
any form of outlier removal, from which all calibration methods could benefit.

**4. _Grip_ gaze estimation [4]**

Status: This should be mostly trivial to add.
Pupil also makes use of the Świrski eye model and unprojections, so it should be
a matter of making the unprojected ellipse's normal vector accessible to the
gaze estimation layer. In EyeRec nomenclature, I refer to this as the
instantaneous gaze vector (in contrast to the regular gaze vector yielded by the
Świrski model).
For the polynomial fit gaze estimation, it's just replacing the pupil
coordinates by the normal vector angles in spherical coordinates.
For the model-based gaze estimation, it is necessary to ignore the per-frame
estimate eye center, replacing it by zeros, or by a fixed eye center estimated
during calibration.

[1] Santini, Thiago, Wolfgang Fuhl, and Enkelejda Kasneci. "PuRe: Robust pupil detection for real-time pervasive eye tracking." Computer Vision and Image Understanding 170 (2018): 40-50.

[2] Santini, Thiago, Wolfgang Fuhl, and Enkelejda Kasneci. "PuReST: robust pupil tracking for real-time pervasive eye tracking." Proceedings of the 2018 ACM symposium on eye tracking research & applications. 2018.

[3] Santini, Thiago, Wolfgang Fuhl, and Enkelejda Kasneci. "Calibme: Fast and unsupervised eye tracker calibration for gaze-based pervasive human-computer interaction." Proceedings of the 2017 chi conference on human factors in computing systems. 2017.

[4] Santini, Thiago, Diederick C. Niehorster, and Enkelejda Kasneci. "Get a grip: slippage-robust and glint-free gaze estimation for real-time pervasive head-mounted eye tracking." Proceedings of the 11th ACM symposium on eye tracking research & applications. 2019.

**Comment by Christopher22** [comment] 2020-06-02 10:04
Amazing if this would work out, @tcsantini ! Just to mention it: Another version of PuRe for Pupil Labs is already out [here](https://github.com/pupil-labs/pupil/pull/1198). At the time of development, it was just not possible to include it due to the choosen Open Source License.

**Comment by tcsantini** [comment] 2020-09-20 20:26
I've started decoupling the methods from EyeRecToo into a library at [https://github.com/tcsantini/eyerec](https://github.com/tcsantini/eyerec). 
PuRe and PuReST are already available.

The methods are accessible through Python with the following package: [https://github.com/tcsantini/eyerec-python](https://github.com/tcsantini/eyerec-python). This package is already pip-installable from the repository (although one has to locally clone it and update the submodule of the aforementioned library until I figure out how get pip to work with the submodule). I'll look into making the package available through PyPi.

**Comment by papr** [comment] 2020-10-07 14:58
Dear @tcsantini,

Thank you for providing a nice overview of EyeRecToo features. At this point, I would like to clarify that the Pupil Core software ships with only one of the listed features [3], which is attributed in our documentation.

We have indeed implemented an open-source version of PuRe based on your paper [1]. An internal evaluation of the current 2D detector, the EyeRecToo PuRe implementation, and our own PuRe implementation has shown three things:
- The PuRe implementations are more accurate at detecting pupils in difficult situations
- The current 2D detector is more accurate at detecting pupils in easy situations
- The current 2D detector allows for better filtering of high-quality data via confidence

In other words, if we wanted to only detect 2d pupil ellipses we would replace the current 2D detector with the open-source PuRe implementation. However, in the default use case, the Pupil Core software uses the 2d pupil ellipses only as a stepping stone to build the 3d eye model. This requires only a few but very accurate ellipse estimations. Based on our evaluation, the current 2D detector is the better fit for this job due to its more precise confidence assignment. Independently of this evaluation, we are able to achieve higher frame rates with the current 2D detector. Therefore, we have decided to continue shipping the current 2D detector and not to replace it with our open-source PuRe implementation.

We are also not planning on shipping the PuReST pupil tracker by default.

Instead, we are working actively on making it easier for the community to integrate and provide core algorithms as user plugins. With Pupil Core v2.0, we have taken the first step in this direction by supporting user plugins implementing calibration procedures and gaze mapping algorithms. In the near future, we will support user plugins implementing pupil detection algorithms, too.

It would be great if someone would implement the core EyeRecToo algorithms as Pupil Core compatible plugins. If/when this happens, we would be happy to include the plugins in the Pupil community repository: https://github.com/pupil-labs/pupil-community

Therefore, we have decided to close this issue for now as we will not be implementing/adding EyeRecToo features to the default Pupil Core stack. We would be happy to continue the discussion via email or chat.

**Closed by papr** 2020-10-07 14:58 UTC

**Comment by tcsantini** [comment] 2020-10-11 17:12
Dear @papr,

Thanks for the clarification!

Given the premise of easy situations, it makes sense to keep the 2D detector if it yields better discrimination of high quality estimates. In fact, PuRe's confidence does not represent probabilities, and I recommend just using a single threshold of 0.66.
_Would it be possible to share your evaluation with the community?_



I think there was a bit of misunderstanding with the nomenclature here; my goal wasn't contributing method directly to **Pupil Core**.
I'm glad to (slowly) add these methods as parts of the **Pupil software stack** (as Pupil plugins) -- tracking that was the purpose of this issue; I wasn't expecting you guys to maintain any of it :-)

The issue was created here because I was informed by email that your version of PuRe would find its way into Pupil Capture via an update around March. Thus, I thought it would be better to clarify and document what was already available from your side instead of guessing it based on the source code.



Anyway, a couple question regarding the pupil detection plugins:
1. I thought it was available as [PupilDetectorPlugin](https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/pupil_detector_plugins/detector_base_plugin.py#L40); _do you have a timeline for when it will be actually ready?_
2. _Is an interface for pupil trackers planned?_
3. _Will the eye model be decoupled from pupil detection in the future?_

**Comment by papr** [comment] 2020-10-14 10:02
Hi @tcsantini

Please see my notes below regarding your technical questions:
1. Yes, `PupilDetectorPlugin` is the official entrypoint if you want to integrate a pupil detection algorithm into Pupil. The issue is that it is currently not yet possible to write these as user plugins (a). We are planning to support user pupil detector plugins within the next 2 releases.
2. We are not planning a special interface for pupil trackers. `PupilDetectorPlugin` should be powerful enough to support pupil tracking since the instance is free to keep its own state. If we are missing something particular that prevents pupil tracking please let us know.
3. We will not separate the 3d eye model from the [current 3d detector](https://github.com/pupil-labs/pupil-detectors/blob/master/src/pupil_detectors/detector_3d/detector_3d.pyx#L37). Instead, you will have the possibility to pass 2d pupil datums to our [upcoming pye3d detector](https://github.com/pupil-labs/pye3d-detector/blob/71f8c4fae7463c6d31b1f8f6473aa033f11a664c/pye3d/detector_3d.py#L147) or use its [TwoSphereModel](https://github.com/pupil-labs/pye3d-detector/blob/71f8c4fae7463c6d31b1f8f6473aa033f11a664c/pye3d/two_sphere_model.py#L33) on its own [5, 6].

(a) User plugins are not shipped within the bundle but are required to be downloaded and placed in `pupil_*_settings/plugins` by the user.

[5] K. Dierkes, M. Kassner, A. Bullling, A novel approach to single camera, glint-free 3D eye model fitting including corneal refraction, ETRA ’18: Symposium on Eye Tracking Research and Applications, 2018
[6] K. Dierkes, M. Kassner, A. Bulling. A fast approach to refraction-aware eye-model fitting and gaze prediction. In ETRA ’19: Symposium on Eye Tracking Research and Applications, 2019

**Comment by papr** [comment] 2020-11-17 10:16
With [Pupil v2.6](https://github.com/pupil-labs/pupil/releases/tag/v2.6), it is now possible to create custom pupil detector plugins. We have also added a [special section to our community repository](https://github.com/pupil-labs/pupil-community#pupil-detector-plugins) to feature any community detectors.
