### ISSUE TITLE
Pupil Capture Audio Mode Doesn't work

### ISSUE THREAD

**Issue by fneitzel** [pupil-labs/pupil#651] opened 2017-03-01 14:19 UTC
Hi there again,

We noticed that the audio mode has a malfunction.
Whatever option you choose to hear, the output is always silent.

pupil-capture 0.9.1-7 amd64

Regards

**Comment by papr** [comment] 2017-03-03 13:56
Dear @fneitzel 
just to be sure, did you make sure that the correct audio input source was selected as `Audio Source` in the recorder settings panel? If this is the case, could you upload the `world.wav` off a short example recording?

**Comment by fneitzel** [comment] 2017-03-03 14:25
Hi @papr,

The issue doesn't concern the recorded audio ( I didn't test it yet )

It is about the 'spd-say' voice and calibration sounds. Sorry for beeing too unspecific here.

I hope the screenshot helps:

![sound_mode_issue](https://cloud.githubusercontent.com/assets/10213803/23554483/8c231564-0025-11e7-8a2d-9af4c4835873.png)

**Comment by papr** [comment] 2017-03-03 14:41
Ah, ok, I understand. Could you specify which OS you are using? The code uses different mechanisms depending on the OS.

**Comment by fneitzel** [comment] 2017-03-03 15:03
Ubuntu 16.04 LTS 
Kernel 4.4.0-64
With pupil version: pupil-capture 0.9.1-7 amd64

**Comment by papr** [comment] 2017-03-03 15:22
Ok, can confirm issue when running from bundle. Issue does not exists when running from source.

**Comment by papr** [comment] 2017-03-03 15:55
Ok, the issue is that `platform.linux_distribution()` returns `('debian', 'stretch/sid', '')` when running from bundle and ` ('Ubuntu', '16.04', 'xenial')` when running from source. The audio module behaves differently for these two. Will be fixed with the next bundle.

**Closed by papr** 2017-03-03 15:55 UTC
