### ISSUE TITLE
Eyecam freezes during recording with pupil capture from pupil mobile via network

### ISSUE THREAD

**Issue by ewolf29** [pupil-labs/pupil#1229] opened 2018-07-17 19:34 UTC
System: MacBookPro with High Sierra 10.13.6
Pupil Capture: pupil_v1.7-42-g7ce62c8_macos_x64_cleaned
Pupil Mobile: 0.30.0

Pupil Capture keeps spamming the following error:

```
2018-07-17 20:57:32,814 - eye1 - [ERROR] video_capture.ndsi_backend: Traceback (most recent call last):
  File "shared_modules/video_capture/ndsi_backend.py", line 122, in recent_events
  File "ndsi/sensor.pyx", line 167, in ndsi.sensor.Sensor.get_newest_data_frame (ndsi/sensor.cpp:7692)
ndsi.sensor.NotDataSubSupportedError: 'This sensor does not support data subscription.'
```

Link to complete logfile will follow.

**Comment by papr** [comment] 2018-07-18 15:57
Unfortunately, I was not able to reproduce this issue on Linux.

**Comment by ewolf29** [comment] 2018-07-24 05:50
I will do another test session this weekend. Will you release V1.8 until the weekend?

**Comment by papr** [comment] 2020-11-18 09:14
This issue should be fixed in more recent versions of Pupil Mobile and Capture.

**Closed by papr** 2020-11-18 09:14 UTC
Labels: dependency: pyndsi, product: Pupil Mobile
