### ISSUE TITLE
GLFW window failed to create (Windows Pupil Player)

### ISSUE THREAD

**Issue by weixulu** [pupil-labs/pupil#992] opened 2017-12-29 21:32 UTC
I was using Pupil Player (v1.1.2) on Windows for several days, but today I started to get the following message. What could be the cause? Thank you.

MainProcess - [INFO] os_utils: Disabling idle sleep not supported on this OS version.
player - [ERROR] launchables.player: Process player_drop crashed with trace:
Traceback (most recent call last):
  File "launchables\player.py", line 558, in player_drop
  File "shared_modules\glfw.py", line 522, in glfwCreateWindow
Exception: GLFW window failed to create.

System information: 
![image](https://user-images.githubusercontent.com/34948796/34447852-de41f9fa-ecb5-11e7-9c6d-0d3034112238.png)

**Comment by weixulu** [comment] 2018-01-01 19:30
I was able to solved the problem by completely removing the settings file, but it was strange that the problem occurred without me changing any settings

**Comment by genchukov** [comment] 2018-01-15 08:36
Got the same problem it also occured 2 versions ago without changing any settings....I´m not sure which settings file I´ve to remove can you help me there?

**Comment by papr** [comment] 2018-01-16 08:47
Closing this issue due to it being a duplicate of #837

**Closed by papr** 2018-01-16 08:47 UTC
