### ISSUE TITLE
Cyrillic characters in path

### ISSUE THREAD

**Issue by xensey** [pupil-labs/pupil#865] opened 2017-10-13 11:20 UTC
Pupil Player not starting if Cyrillic characters in path to folder, e.g. "C:\Users\Евгений\Pupil"
![pupil-cyr](https://user-images.githubusercontent.com/19759465/31544030-9eaeeb7a-b021-11e7-912f-ee73e90a29e8.png)

**Comment by papr** [comment] 2017-10-16 08:11
I tried to replicate this issue using a virtual environment called "Евгений" on my Linux machine and the cyrillic characters where no issue. I actually suspect the space character before ` (1)` to be problematic. 
@xensey Could you rename the folder such it does not contain spaces?

**Comment by mkassner** [comment] 2017-10-16 15:01
@papr  did you try this on Windows? looking at the screenshot this is on windows.

**Comment by papr** [comment] 2017-10-16 15:04
No, I only tested on Linux. First I wanted to test if the space is the problem, before assuming that it is a Windows-only problem.

**Comment by mkassner** [comment] 2017-10-16 15:08
@papr  I m pretty sure this is an issue we had seen before and where we identified the cause:  https://github.com/memononen/fontstash/issues/28

**Comment by xensey** [comment] 2017-10-16 15:08
Space in folder name - no problem
Cyrillic in folder name - crash
Same problem with cyr when uploading a recording from a folder containing cyrchar, like C:/йзъбюя/001

**Comment by mkassner** [comment] 2017-10-16 15:08
the fix is fixing this issue.

**Comment by mkassner** [comment] 2017-10-16 15:10
@papr  I ll ask @pointcontrols  to have a look.

**Comment by mkassner** [comment] 2017-10-20 14:17
Fixed with https://github.com/pupil-labs/pyglui/issues/44

changes will be in upcoming release.

**Closed** 2017-10-30 14:49 UTC
