### ISSUE TITLE
Separated data for offline calibration and recording? Pupil mobile and player

### ISSUE THREAD

**Issue by AcyEsch** [pupil-labs/pupil#1065] opened 2018-02-08 15:36 UTC
Hi there, I would like to know if I can use calibration data from a recording in pupil player on a different recording. 
The background to this request is that I use pupil mobile and manual marker tracking for calibration. Right now I can only record the markers and the test case together. But if I have poor calibration/marker detection results - which I can only see afterward in pupil player - the whole test recording is useless. It would be easier to record a few times the markers so I can use the best recording for the test case.
A different option to enhance my test results would be to edit the eye data in the player like changing the contrast and then redetect the eyes. This could help a lot too. Thanks.

**Comment by mkassner** [comment] 2018-02-08 16:53
What about running Pupil Capture and realtime wifi stream from Pupil Mobile while recording on the phone to make sure the calibration is right? Seems like that would also solve this problem?

**Comment by AcyEsch** [comment] 2018-02-09 10:49
It needs to work in areas without any wifi connection...

**Comment by mkassner** [comment] 2018-02-09 13:29
good point. What about making one big recording with multiple calibrations and then using the calibration range to select the right one?  Also note that you can tweak all pupil detection params and ROI in the eye window during detection in Player after the fact, then hit redirect to apply the changes to the entire video.

**Comment by AcyEsch** [comment] 2018-02-09 13:56
Thanks! Didn't see that possibility. I will try this out.

**Comment by papr** [comment] 2018-02-22 14:05
Duplicate of #1003

**Closed by papr** 2018-02-22 14:05 UTC
