### ISSUE TITLE
Pupil Player will not open on Mac 

### ISSUE THREAD

**Issue by SarahB96** [pupil-labs/pupil#1502] opened 2019-05-07 16:29 UTC
I am trying to set up Pupil labs on a MacBook Air (Mojave) for an experiment. I was able to calibrate and record data with Pupil Capture. However, when I try to open pupil player, it crashes immediately. 

If I go to the pupil_player_settings > player log it says: "Please drag a Pupil recoding directory onto the launch icon." I am not sure what to do...

**Comment by willpatera** [comment] 2019-05-14 04:13
@SarahB96 I tested Player on MacBook Air `v10.14.3` (Mojave) with a recording made with `v1.12` release. 

I was **not** able to reproduce the behavior you observed. Can you please try deleting `pupil_player_settings` and then re-open Player?

**Comment by papr** [comment] 2019-05-29 12:14
@SarahB96 were you able to follow Will's tips? Did it work? I would like to find a solution for this issue. 👍

**Comment by SarahB96** [comment] 2019-05-29 14:02
I still cannot open pupil player. Here is the message I get: __Player: 2019-05-29 10:00:16,320 - __main__ - WARNING - You did not supply a data directory when you called this script!                    
Please drag a Pupil recoding directory onto the launch icon.__

**Comment by papr** [comment] 2019-05-29 14:12
Could you please try to drag the folder that includes the video files and info.csv file onto the gray area of the window?

**Comment by SarahB96** [comment] 2019-05-29 14:33
The problem is that I cannot even open the app at all, it is as if it crashes before it is even open.

**Comment by SarahB96** [comment] 2019-05-29 14:33
I have watched videos/seen pictures of people dragging the video files in the grey area but i cannot even get to the grey area

**Comment by LHicken** [comment] 2019-06-24 18:57
I'm having a similar issue on a Mac Air. I download the apps, but when I try to open them, I get a message saying the app is damaged and should be moved to the trash. I've tried deleting the settings, but this is still happening. Thanks in advance for your help!

**Comment by LHicken** [comment] 2019-06-24 18:59
I was able to download and open the apps on a Macbook Pro. But that computer doesn't belong to me, so I want to figure out the issue on my personal Macbook Air. Thanks!

**Comment by papr** [comment] 2019-07-21 16:55
If the problem still persists, please download the newest version from the Github release page. In case the newest bundle still does not work as expected, please let us know and we will reopen this issue.

**Comment by emjohns32** [comment] 2019-07-24 18:04
I would like to reopen this issue. I have been working with the same OS, but am having a slightly different issue. The application will not even open for me. I also do not have this pupil_player_settings folder to delete.

**Comment by SarahB96** [comment] 2019-07-24 18:42
I am also having a huge problem because I finally got it to work but the program keeps crashing on my Mac.

I am wondering if there is a minimum RAM requirement?

--
Sarah Benkirane, B.A. Hons.
Étudiante au doctorat / Ph.D. Student
CIEL - Laboratoire de Recherche sur la Culture l'Identité et la Langue
Département de psychologie
Université du Québec à Montréal
C.P. 8888, Succursale Centre-Ville<x-apple-data-detectors://2/0>
Montréal (Québec) CANADA<x-apple-data-detectors://2/0>  H3C 3P8
E-mail: benkirane.sarah@courrier.uqam.ca<mailto:benkirane.sarah@courrier.uqam.ca>
ciel.uqam.ca<http://ciel.uqam.ca/>

Le 24 juill. 2019 à 14:06, emjohns32 <notifications@github.com<mailto:notifications@github.com>> a écrit :


I would like to reopen this issue. I have been working with the same OS, but am having a slightly different issue. The application will not even open for me. I also do not have this pupil_player_settings folder to delete.

**Comment by papr** [comment] 2019-07-24 18:46
Please share your Capture.log files after the program crashed.

**Comment by xmokry** [comment] 2019-08-08 16:30
Same here. Unfortunately, I am not able to open Pupil Capture. My OS is Mojave 10.14.6. I was able to open Pupil Capture once after a new installation, but the eye window was completely grey. After closing the app, now I'm not able to open it. It only appears in the dock but nothing happens.

**Comment by papr** [comment] 2019-08-08 17:02
@xmokry Please share your Capture.log files after the program crashed.

**Comment by rucua** [comment] 2020-01-23 18:04
I can't open both Pupil capture and Pupil Player in OS X 10.10.5. Previous version (1.13) worked OK. 
Yesterday, I updated from 1.13 to 1.21 and the app does not open now. It does nothing: not app window, not app icon in OSX Dock.

**Comment by samhforbes** [comment] 2020-03-09 17:13
It looks like we also can't use any version after 1.13 as well, for the same reason that @rucua has noted.

**Comment by mpopopa** [comment] 2020-04-03 14:46
I think I'm having the same problem. When I ran Pupil Player, it creates "pupil_player_settings" folder under my home directory, and that's it. Any thought? I'm downloaded pupil_v1.23-0-g1218905e_macos_x64.zip, so I believe this is the newest version.

**Comment by papr** [comment] 2020-07-13 10:21
Please be aware that starting with Pupil v2.0, we require macOS 10.13 High Sierra or later. Unfortunately, there is an issue when running Pupil Capture on macOS 10.14.6 (#1919) which has been fixed in #1966 and will be included in our upcoming v2.1 release.

**Closed by papr** 2020-07-13 10:21 UTC
Labels: os: macOS
