### ISSUE TITLE
Windows bundle - world crash on minimize while recording

### ISSUE THREAD

**Issue by cpicanco** [pupil-labs/pupil#139] opened 2015-04-17 19:04 UTC
Hope you can reproduce this one.

**Comment by MichaelBarz** [comment] 2015-04-21 12:17
I could not reproduce this one. I used "color" for world and "algorithm" for eye and minimized both via "the minimize icon", "alt+tab" and the windows "minimize all" (click at the right border of the task bar).

Did you use differing settings?

Best, Michael

**Comment by cpicanco** [comment] 2015-04-21 15:33
I was using Windows + M. I experience this one multiple times when making the "performance report". 

Open Pupil capture
Start Recording
Press windows + m
Switch to world with Alt + Tab
The world window gets unresponsive.

**Comment by MichaelBarz** [comment] 2015-04-22 13:52
This scenario works for me. Maybe the new bundle solved this already. There will be a test bundle 3 soon.

**Comment by mkassner** [comment] 2015-04-22 16:25
available now.

**Comment by cpicanco** [comment] 2015-04-22 16:38
will test this today

**Comment by cpicanco** [comment] 2015-04-22 18:27
Bug persists with new bundle

**Comment by MichaelBarz** [comment] 2015-04-23 08:10
Ok, maybe a setting or plugin causes this behavior. Could you tell us, what plugins were open and what settings you applied for those plugins. Then we can try to reproduce the issue with these settings.

**Comment by cpicanco** [comment] 2015-04-23 17:02
There is no way of running the bundle through something like the terminal? I have tried with cmd.exe, but world and eye processes are not executed "attached" with the cmd.exe.

**Comment by cpicanco** [comment] 2015-04-23 17:08
I hate intervalar bugs (error code 40: #135 ).

Here is the world.log:

```
World Process: 2015-04-23 13:54:05,986 - video_capture - WARNING - Found [u'Logitech HD Webcam C615'] as devices that match the src string pattern Using the first match.
World Process: 2015-04-23 13:54:05,986 - video_capture.win_video - WARNING - Capture device does not support preferred frame-rate 24
World Process: 2015-04-23 13:54:11,012 - video_capture.win_video - ERROR - Could not setup capture device. Error code: 40
vid_046d&pid_082c&mi_02#7&13a939ca&0&0002#{e5323777-f976-4f5b-9b55-b94699c46e44}\{bbefb6c7-2fc4-4139-bb8b-a58bba724083}
World Process: 2015-04-23 13:54:06,762 - plugin - INFO - Loading plugin: Dummy_Gaze_Mapper with settings {}
World Process: 2015-04-23 13:54:06,762 - plugin - INFO - Loading plugin: Display_Recent_Gaze with settings {}
World Process: 2015-04-23 13:54:06,762 - plugin - INFO - Loading plugin: Screen_Marker_Calibration with settings {}
World Process: 2015-04-23 13:54:06,762 - plugin - INFO - Loading plugin: Recorder with settings {}
```

**Comment by MichaelBarz** [comment] 2015-04-23 17:25
Ok, error code 40 is: VIDEOCAPTUREDEVICE_DEVICESTART_WAIT_TIMEOUT. This is an error code of the video backend we use. I'm not quite sure why a "start" error ocurrs during runtime, after the device started successfully. Seems that returning to the world window takes too long.
I'll try to reproduce the error with an i3 machine (you have an i3, right?)... up to now I tried with a Core2Quad only.

I guess there are two possible solutions:
* enhance performance of our code (e.g. do not update, when minimized)
* increase the timeout (if possible)

Best, Michael

**Comment by cpicanco** [comment] 2015-04-23 17:33
Just for note, I am trying to reproduce the log message, but I can't. Now all that is logged is that (note the non printable chars in front of the first message):

```
                                                                                                                                                                                                                                                                                                                 World Process: 2015-04-23 14:29:34,278 - video_capture - INFO - Camera selected: Logitech HD Webcam C615  with id: \\?\usb#vid_046d&pid_082c&mi_02#7&13a939ca&0&0002#{e5323777-f976-4f5b-9b55-b94699c46e44}\{bbefb6c7-2fc4-4139-bb8b-a58bba724083}
World Process: 2015-04-23 14:29:34,480 - plugin - INFO - Loading plugin: Dummy_Gaze_Mapper with settings {}
World Process: 2015-04-23 14:29:34,480 - plugin - INFO - Loading plugin: Display_Recent_Gaze with settings {}
World Process: 2015-04-23 14:29:34,480 - plugin - INFO - Loading plugin: Screen_Marker_Calibration with settings {}
World Process: 2015-04-23 14:29:34,480 - plugin - INFO - Loading plugin: Recorder with settings {}
```

**Comment by cpicanco** [comment] 2015-04-23 17:37
![image](https://cloud.githubusercontent.com/assets/6511849/7303324/30427afe-e9c6-11e4-9b99-f372989e5dc0.png)

**Comment by MichaelBarz** [comment] 2015-04-23 17:48
Ok, this should not be the reason. I got 4x2.5GHz.
I can re-try to setup the device if, e.g. a timeout was reported. But this should help for the startup only.

I'll try the following:
* [ ] Re-try setting up camera, if it failed at startup
* [ ] Re-init camera, if frame grabbing failed n times during runtime

**Comment by cpicanco** [comment] 2015-04-23 18:00
I think that windows is hidding some error messages after its first occurence. I could reproduce the error #135 by closing the application, after rebooting and after world window becoming unresponsive. It makes any sense to you??

**Comment by MichaelBarz** [comment] 2015-04-28 11:22
Hmm... does not make many sense to me.
However, I implemented the error recovery as stated above.
Hopefully this also solves your problem...

**Comment by mkassner** [comment] 2015-05-04 07:14
I ll close this for now. @cpicanco reopen if you should have this error with the new version.

**Comment by cpicanco** [comment] 2015-09-05 15:14
Hi, @mkassner , I can't reopen this Issue. Only colaborators can reopen issues closed by owners.

**Comment by mkassner** [comment] 2015-09-05 21:46
Ok. Done

**Comment by MichaelBarz** [comment] 2015-09-08 08:09
Hi, this time I could reproduce the error. A glCheckError occurs in gl_utils.utils, line 93, exactly when minimizing the world window. I guess it is not possible to project a texture to a minimized window on Windows. @mkassner, do you have an idea how to solve this opengl issue? Maybe a check on the window state, minimized or not, could solve the issue. Find the complete console output below:
![min_error](https://cloud.githubusercontent.com/assets/6330614/9729722/ad4f567c-5611-11e5-8b9a-27e9595018f7.png)

**Comment by MichaelBarz** [comment] 2015-09-08 08:20
In addition this happens when minimizing pupil capture without the record function being active and also for the eye window.

**Comment by mkassner** [comment] 2015-09-09 06:59
I m pretty sure this is windows gl being different (and annoying). When a window is iconified it appears that under windows the gl context is funny, either the size is 0,0 or its simple not valid. 

I made changes to skip rendering when the window is iconified but I still allow plugins to render. So please check if the changes fix the problem for you.

**Comment by MichaelBarz** [comment] 2015-09-09 09:57
Ok, your fix works!

**Closed by MichaelBarz** 2015-09-09 09:57 UTC
Labels: Bundle, Windows
