### ISSUE TITLE
Data loss - Pupil detection

### ISSUE THREAD

**Issue by nadinagomez** [pupil-labs/pupil#1494] opened 2019-04-29 08:43 UTC
Hi, we are conducting an experiment and we don't have the World camera as we are just interested on the pupil diameter. We made a sample recording and confidence Interval didn't keep constant across the experiment, this result in a 44% data loss ( in a 2 minuts task) which is not ok for the experiment. We have checked all the pupil detection parameters and they were into a high confidence Interval. What could we do to ensure a good pupil diameter  confindence recording along the experiment?
Also, what program do you suggest when exporting data? (Excel, Numbers, etc

**Comment by papr** [comment] 2019-04-29 14:30
What is your confidence interval? Also, please share an example recording with data@pupil-labs.com such that I can check what is causing the confidence drops.

Player exports the data in the csv file format. Afterwards, you can use the post-processing software of your choice.

**Comment by nadinagomez** [comment] 2019-04-29 15:06
Dear Pablo, I've just send a sample of the data. There are other issues I'd
appreciate to know:
We want to measure cognitive effort among children during an auditory task
, we're not interested in where are they looking at (that's why we don't
have a world camera ) but we want to allow them to move their head free as
they are little children. However , we can't afford data loss, are this
glasses appropiate to capture this data?  We know calibration doesn't make
a sense but we want to make sure we don't miss the data, how can we be sure
about this?

Also, does It help to chance to a lower rate sampling ? E.g. from 200Hz to
60Hz

Do you recommend us to use the 2D or the 3D?

About the data, we hace activated the blink detection plugin , are this
blinks included in the pupil position document? (They should appear as
lower confidence data I Guess) in that case , Who can identify them?

Thanks in advance for your help.

**Comment by papr** [comment] 2019-05-17 07:55
Dear @nadinagomez 

Apologies for the late reply.

After looking at your recording, I recommend to use Offline Pupil Detection (after-the-effect pupil detection in Pupil Player) using the 2D mode. Your recording has a lot of slippage which results in the 3d model to refit very often in 3D mode. During the refits, the pupil diameter is less accurate since it is calculated based on the older model. In 2D mode, the diameter is calculated on a per frame basis and is therefore less prone to the effects of slippage. Please be aware that the 2D mode measures the pupil diameter in image pixels and not in millimeters.

I would recommend to run the eye camera at 200Hz since this will give you the highest amount of samples.

In Player, detected blinks are exported to a separated document `blinks.csv`. It includes information about the start and end time and indices of the blink.

I will close this issue as I believe that we have responded to the question. If you feel otherwise, please make a comment and we can continue to discuss.

**Closed by papr** 2019-05-17 07:55 UTC
Labels: question

**Comment by nadinagomez** [comment] 2019-05-17 08:35
Thanks for your valuable response, so:
- How do we select offline detection ? is It done by selecting the 2D Mode?

**Comment by papr** [comment] 2019-05-17 09:08
@nadinagomez Please check out the first half of our [_Offline Pupil Detection and Offline Calibration_ screen cast](https://www.youtube.com/watch?v=_Jnxi1OMMTc&list=PLi20Yl1k_57rlznaEfrXyqiF0sUtZMMLh&index=2&t=0s)

**Comment by nadinagomez** [comment] 2019-05-26 09:25
Dear Pablo, there's another issue we have, we are using the binocular
recording (with both Eye cameras) no world camera. However during the
recording ,occasionally ,the diameter  goes Up to extrem and imposible
values (such as 20mm) , sometimes this values are shown even with high
confidence (as shown in the confidence graph)We've tried to use a 2D Mode
instead Than 3D but the confidence drops with 2D.

What could be this related to?  Could It depen on the parameters we set?
(Ex. Pupil min and Max and pupil intensity range) we set the pupil min and
Max by values between 20 and 100 respectively so that the green circle
remains between the boundaries of the red ones, however we don't know which
would be the correct values for the  number that appears displayed in the
center. We also adapt the pupil range to cover in blue the pupil área.
Please could you help us? This extreme values are not acceptable for using
the device reliably for our study, and we need to make sure If can trust on
the data yo derive our hyphotesis. We have limited time as our assesments
are planned to start soon, so would appreciate a lot your help.

**Comment by papr** [comment] 2019-05-27 08:35
Duplicate of #1513
