### ISSUE TITLE
Exporting Data

### ISSUE THREAD

**Issue by mahmoudgaber1992** [pupil-labs/pupil#1670] opened 2019-10-03 15:13 UTC
when I export a video the work i added to the video (Eye movement) doesn't appear in the exported one.
what seems to be the problem ?

**Comment by papr** [comment] 2019-10-03 15:20
Hi @mahmoudgaber1992 the visualization of the eye movement detector should be visible in the exported world video. Were you referring to this video, or the eye videos?

**Comment by mahmoudgaber1992** [comment] 2019-10-03 15:27
yes I checked the world video and my editing did not appear in it.

**Comment by papr** [comment] 2019-10-03 15:32
Can you see the eye movement visualizations in the Player window? 

Please be also aware that the exported video is saved to the exports folder of your recording.

**Comment by mahmoudgaber1992** [comment] 2019-10-03 15:46
yes i can see the eye movement visualization in the player window and i am opening the video from exports.
The problem is that i can only see eye movement in the original video but not in the extracted video.

**Comment by papr** [comment] 2019-10-03 16:18
Sorry, I am not clear on what you mean by original video. Could you make a screen recording of your work flow? Maybe I can tell based on it if our work flows differ. Also, could you share the recording with data@pupil-labs.com such that I can try to reproduce the issue?

**Comment by mahmoudgaber1992** [comment] 2019-10-03 16:45
i sent you a recorded video by we transfer to the email    data@pupil-labs.com

**Comment by papr** [comment] 2019-10-03 17:09
Thank you very much, this was very helpful! Could you let me know if you are running the most recent `v1.16-80` Pupil Player version?

**Comment by mahmoudgaber1992** [comment] 2019-10-03 17:28
Now, yes but I get the same result ( no eye movement detector on the exported video)

**Comment by papr** [comment] 2019-10-03 17:34
Ok, thank you for your feedback. Could you share the raw Pupil recording with data@pupil-labs.com so I can try to reproduce the issue locally?

**Comment by mahmoudgaber1992** [comment] 2019-10-03 17:47
i sent you the raw Pupil recording by we transfer to the email data@pupil-labs.com

**Comment by papr** [comment] 2019-10-03 18:01
Thank you very much. I was able to reproduce the issue. We will try to find the underlying bug and let you know as soon as we know more!

**Comment by papr** [comment] 2019-10-08 11:16
@mahmoudgaber1992 The issue is that for the export to work, the eye movement data is read from disk. This data is currently only stored to disk if Player is shut down.

We will add a fix for this issue to our next release such  that the data is cached as soon as the plugin has completed detection.

Until then, you can work around the issue by enabling the detector, run the detection until it is completed, restart Player, and run the world video export.

**Closed** 2019-10-08 13:06 UTC
