### ISSUE TITLE
Synchronization Drift between Cameras and Recording Computer

### ISSUE THREAD

**Issue by behinger** [pupil-labs/pupil#1266] opened 2018-08-14 09:27 UTC
Hi!
I previously discussed this issue with @papr, he also helped diagnose the problem at our institute. 

## Background
Our setup consists of a USB3 Binocular 120Hz Pupillabs Eyetracker. We use pupil capture 1.6 compiled to record the data. 

We record ET data and send zmq "triggers" (msgs for which we announce the current timestamp g_pool.get_timestamp(), to align the recording with the experiment) using the following code:

```python
t = self.g_pool.get_timestamp()
t_frame =self.g_pool.capture._recent_frame.timestamp
notification = {'subject': 'trigger', 'label': msg, 'timestamp': t, 'recent_frame_timestamp':t_frame, 'duration': 0.0, 'record': True}
ipc_pub.notify(notification)
response = 'nbp_ok'
socket.send_string(response)
```

## Drifts
We noticed drifts between the msg timestamp and the camera timestamps (e.g. finding the frame of the world video when the stimulus onset occurs and checking the timestamp of the zmq-message). We therefore now always also save the g_pool.current_timeframe whenever we send a message, so that we can later remove the linear drift of camera vs. computer. (ZMQ-Messages are in computer time, camera-frames in camera-time).

Top row shows beginning 10 messages, bottom row last 10 messages. Direct difference-curves can be seen further down. A clear drift appears. The recordingsession was ~1h in this case
![grafik](https://user-images.githubusercontent.com/10183650/44083379-1b21ad50-9fb4-11e8-9015-8d9256c88dd6.png)

![](https://placehold.it/15/AA25AA/000000?text=+) Message Timestamp
![](https://placehold.it/15/25AA25/000000?text=+) Camera Timestamp

Note that these drifts can be as large as 300ms!

## How to HOTFIX it
We use robust linear regression to fit the messages to the camera. Afterwards we only need to remove the 45ms delay of the cameras and we then should be in "trigger-time", that is synchronous to the send zmq-messages.
```python
def pl_fix_timelag(pl):
    #fixes the pupillabs latency lag (which can be super large!!)

    t_cam = np.asarray([p['recent_frame_timestamp'] for p in pl['notifications'] if p['subject']=='trigger'])# camera time
    t_msg = np.asarray([p['timestamp'] for p in pl['notifications'] if p['subject']=='trigger']) # msg time
    
    #slope, intercept, r_value, p_value, std_err  = scipy.stats.linregress(t_msg,t_cam) # predict camera time based on msg time
    slope,intercept,low,high = scipy.stats.theilslopes(t_cam,t_msg)
    logger = logging.getLogger(__name__)
    logger.warning("fixing lag (at t=0) of :%.2fms, slope of %.7f (in a perfect world this is 0ms & 1.0)"%(intercept*1000,slope))
    # fill it back in
    # gonna do it with a for-loop because other stuff is too voodo or not readable for me
    
    for ix,m in enumerate(pl['notifications']):
        pl['notifications'][ix]['timestamp'] = pl['notifications'][ix]['timestamp']  * slope + intercept + 0.045 # the 45ms  are the pupillabs defined delay between camera image & timestamp3
        
    return(pl)
```
### Examples of drift subjects:
![#1589F0](https://placehold.it/15/1589F0/000000?text=+) difference between timestamps before correction
![#f03c15](https://placehold.it/15/f03c15/000000?text=+) difference after correction
![grafik](https://user-images.githubusercontent.com/10183650/44082270-ff012180-9fb0-11e8-8676-2c1b55ae1440.png)
![grafik](https://user-images.githubusercontent.com/10183650/44082288-0c26cedc-9fb1-11e8-9087-f2c0125a8b5a.png)

### Examples of normal subjects
![grafik](https://user-images.githubusercontent.com/10183650/44082308-1d23e648-9fb1-11e8-838f-1713b2218984.png)
![grafik](https://user-images.githubusercontent.com/10183650/44082325-26b20226-9fb1-11e8-91d2-b2cb7f8414c8.png)

The spikes you see in both recordings are due to bug #1204.

## Incidence Rate
We found these drifts in 6  / 17 = 33% of subjects. The equipment was not changed (except replugging / reboots) between recording sessions.

**Comment by mkassner** [comment] 2018-08-23 15:59
@behinger  What OS are you using? Does this also occur on more recent version of Pupil Capture?
@pointcontrols  can you try to reproduce this?

**Comment by mkassner** [comment] 2018-08-23 16:00
@behinger  and also thank you for the detailed writeup!

**Comment by pointcontrols** [comment] 2018-08-23 16:01
Can you try with something newer than PC 1.6 , best with latest version ?

**Comment by behinger** [comment] 2018-08-24 05:01
Unfortunately, I do not have access to the computer nor the eyetrackers right now.

The OS is Ubuntu 16.04LTS

**Comment by pointcontrols** [comment] 2018-08-27 12:39
@behinger Can you please provide us with your modifications so we can reproduce this?

**Comment by behinger** [comment] 2018-08-27 12:42
what do you mean with modifications? I added the above snippet to the standard pupil notifications/ZMQ plugin.

**Comment by pointcontrols** [comment] 2018-08-27 12:56
@behinger Thanks, during recording has there been any abrupt lighting changes in the scene, or it has been relatively constant?

**Comment by behinger** [comment] 2018-08-27 12:58
There are lighting changes (a pupil dilation test scenario), but its on the luminance range of a monitor.  This happens 6 times during the hour (exemplary data above). But as you can see, the drift is pretty linear over the whole time and seems unrelated to that block.

**Comment by pointcontrols** [comment] 2018-08-30 12:20
@behinger  Fixed in https://github.com/pupil-labs/libuvc/pull/30/commits/872e1264f2b3f8d8ce26778a0874b768ef8fac99 .

**Closed by pointcontrols** 2018-08-30 12:20 UTC

**Comment by juliusverrel** [comment] 2018-08-31 10:04
Same question: Was the bug replicated, and on which OSs? Is there a simple way of finding out whether it occurred in previously recorded data?

**Comment by behinger** [comment] 2018-08-31 11:29
@pointcontrols Thanks and great that you could reproduce it! As I see in your fix you are now trying to estimate the drift through a calibration procedure at the beginning? I still wonder why the drift is sometimes there and sometimes not. I do not understand enough on the technical side unfortunately.

@juliusverrel one way I can think of checking is e.g. if you send trigger when things happened on the screen. You can observe in the worldcamera when the onscreen-change happened and compare it to the actual trigger/notification. This could give you also some datapoints (albeit with only 15/30ms accuracy due to 60/30fps worldcam frequency). If you have enough you can estimate the drift and try to correct for it.

**Comment by pointcontrols** [comment] 2018-08-31 11:32
The actual camera clock frequency is not the one that the device reports
when queried. That's due to variety of factors such as imperfections in
components , temperature, etc.
