### ISSUE TITLE
Eye overlay 3d pupil rendering issue in Pupil Player v2.0 

### ISSUE THREAD

**Issue by VisionResearchBlog** [pupil-labs/pupil#1912] opened 2020-06-12 17:42 UTC
This is actually 2 separate problems, one is that I have some sessions that have been causing the player to freeze when doing surface detection or just playing the video. When the application freezes I have to force quit the program.  I am still trying to sort out what is causing the crashes and will report on that later but for now I'll focus on what happens after the force quit.

When I restart v2.0 Pupil Player it opens a blank black terminal window and a blank white app window and does nothing else. Uninstalling and reinstalling did nothing and I've seen the behavior also in v1.23 so it seems to be how the settings are stored in a location different from the actual install location.

I found that if I run a copy of v1.22 it mentions the session file is for different version and resets things and v1.22 starts normally. If I close v1.22 and then start v2.0, it also starts normally. 

I've been able to reproduce this several times in v2.0 (and also in v1.23). I have sessions saved with v1.12 and it seems like some of these are are sometimes causing the errors where the program freezes. I'd prefer to use v2.0 for improved fixation detection and surface tracking. 

Where are the session settings files are stored on Windows 10? I'd like to make a copy of the settings so I can reinstate them if they get corrupted. With my current solution I have to reset all my plugin settings for eye overlay, surface detection and fixation detection which is annoying to keep redoing as I have ~150 tracking sessions I need to analyze and the error has happened several times today.

**Comment by pfaion** [comment] 2020-06-12 18:33
Hi @VisionResearchBlog,

I'm sorry for the trouble you are having. If you are running Pupil from the downloaded bundles, you can find the session settings in your user's home folder. There will be separate settings for Capture, Player and Service, in the folders `pupil_capture_settings`, `pupil_player_settings` and `pupil_service_settings`.

Regarding Player freezing/not opening: inside the session settings folders you will also find a log file, e.g. `pupil_player_settings/player.log`. We only store the last log file in order not to clutter your hard drive. It would be great if you could share the `player.log` file with us from after these issues occur, so we can get an idea of what's going wrong on your machine.

**Comment by VisionResearchBlog** [comment] 2020-06-16 12:58
Hi Thank you for the info regarding the session settings. Regarding the crashes I did not save the log file from the last one but did take some screenshots. However, note when this error occurred the settings files weren't corrupted. I'll update the next time I can recreate the problem
![error](https://user-images.githubusercontent.com/17455592/84777354-01b6bc00-afd1-11ea-8b4c-2e584aff787b.JPG)
![error2](https://user-images.githubusercontent.com/17455592/84777360-04191600-afd1-11ea-8c2d-f1f43448a4fb.JPG)

**Comment by pfaion** [comment] 2020-06-16 13:44
Hi @VisionResearchBlog 
thanks for sharing the screenshot! A couple of questions:
1. Do you still have the recording that caused this crash?
  If yes, could you share it with us, e.g. by zipping it and uploading it to a file sharing service such as Google Drive or Dropbox and sharing it with data@pupil-labs.com?
2. Did you experience this issue more often?

**Comment by VisionResearchBlog** [comment] 2020-06-18 15:30
Hi I am uploading the datafile that causes the crash now. I just recreated the error by loading the file. The fixation finder updated and then I clicked on the surface tracker button but did not adjust any settings. I moved the video viewer time selection around back and forth on the time line and the window stopped responding a bit - I've attached a screenshot and the log file
![000_error_June18](https://user-images.githubusercontent.com/17455592/85040667-90b20880-b178-11ea-89e5-b878b58dc4a2.JPG)
[player.log](https://github.com/pupil-labs/pupil/files/4799521/player.log)

**Comment by VisionResearchBlog** [comment] 2020-06-18 15:34
Note this crash does not result in the settings files being corrupted unlike the title of this thread- I have not been able to recreate that error yet

**Comment by papr** [comment] 2020-06-22 09:10
I have renamed the issue appropriately.

**Comment by pfaion** [comment] 2020-06-23 10:03
Hi @VisionResearchBlog,
this crash seems to be caused by some faulty data produced by the 3D pupil detector.
More specifically: the computed circle of the eye-ball outline has a negative width in some frames.

We have not seen this issue before and cannot immediately explain it.
It might be a very rare edge case.
I also noticed that this recording was made with Pupil v1.12, so it might be that this issue has been fixed in the past already.
We will take a look at how this data could have been produced by the 3D pupil detector, but finding the cause might prove difficult without being able to reproduce the error locally.

In the meantime, we will create a fix that prevents Pupil Player from crashing when this kind of faulty data occurs.
We will release the fix in the next version.

**Comment by VisionResearchBlog** [comment] 2020-06-23 10:08
Thanks for the explanation @pfaion - I have several videos recorded last year with v1.12 that I am analyzing. If I end up finding more files that create this crash, would re-running pupil detection, calibration, and gaze mapping get around this issue?

**Comment by pfaion** [comment] 2020-06-23 10:32
@VisionResearchBlog In theory this could solve the issue, assuming that the pupil detector won't output the same faulty data (which seems to be highly unlikely). However, this might produce suboptimal results if you have not included a phase at the start of the recording where the 3D eye model can converge. I quickly tested this with the recording you sent and this seems to be a problem here.

As an explanation: the 3D eye model used for the 3D pupil detector adapts itself over time to compensate for slippage of the headset. Because of this, it does not work well immediately at the start, but needs to receive gaze data from different angles to converge on a good fit for the underlying eye. Since the offline pupil detector starts from scratch, not having recorded such a phase at the start will result in a badly fitted 3D model.

We will try to release a new version with the fixes as soon as possible.
And since we have never seen this happening before, I'm rather confident that you won't run into this issue again.
But if you do, please let me know!

**Comment by papr** [comment] 2020-07-07 08:14
Fixed in #1947 and #1954

**Closed by papr** 2020-07-07 08:14 UTC
