### ISSUE TITLE
Pupil Invisible Monitor Mac cannot launch

### ISSUE THREAD

**Issue by bhouDTU** [pupil-labs/pupil#2154] opened 2021-06-25 10:13 UTC
Hi, 

I am trying to view the Pupil Invisible recording in realtime on a laptop, using your Pupil Invisible Monitor app. I am using macbook pro m1. 

I downloaded the Mac version from https://github.com/pupil-labs/pupil-invisible-monitor/releases/tag/v1.3#user-content-downloads. When I tried to launch it, it says "Apple cannot scan malicious..." so I set the system preference - security and privacy to open it anyway. 

I click on the icon again but nothing happens, the app does not launch. 

Your help would be much appreciated. 

Thanks,
James

**Comment by papr** [comment] 2021-06-25 10:27
Hi, the issue is that the uploaded bundle was not yet notarized by Apple. Please see use this [notarized version](
https://github.com/pupil-labs/pupil-invisible-monitor/releases/download/v1.3/pupil_invisible_monitor_mac_os_x64_v1.3-10-g1f171da-notarized.dmg) instead. I also uploaded it to the release page.

Please note, that we have not tested this application on M1 macs yet. It is possible that the application does not behave as expected.

Also, please report issues to the application/module-specific repositories in the future, e.g. https://github.com/pupil-labs/pyndsi/ for issues with pyndsi

**Comment by bhouDTU** [comment] 2021-06-25 10:41
Thanks @papr , I downloaded the notarised version. It still does not launch. Could be an M1 issue, like you said. I would be grateful to hear any suggestions you may have on monitoring realtime recording on Mac m1 laptop.

Yes, I will remember to report to specific repositories in the future.

**Comment by papr** [comment] 2021-06-25 10:50
@bhouDTU Thanks for testing. Could you please run the application from the terminal like this `/Applications/Pupil\ Invisible\ Monitor.app/Contents/MacOS/pupil_invisible_monitor` (you might need to adjust the path if you did not install the application to `/Applications`). It should give you information about the issue.

**Comment by bhouDTU** [comment] 2021-06-25 10:54
Thanks @papr , I appreciate your help. I got the following error messages:

(PINetwork1) baoho@jamess-mbp ~ % /Applications/Pupil\ Invisible\ Monitor.app/Contents/MacOS/pupil_invisible_monitor
Traceback (most recent call last):
  File "PyInstaller/loader/pyiboot01_bootstrap.py", line 149, in __init__
  File "ctypes/__init__.py", line 364, in __init__
OSError: dlopen(OpenGL, 10): image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "OpenGL/platform/darwin.py", line 38, in GL
  File "OpenGL/platform/ctypesloader.py", line 45, in loadLibrary
  File "PyInstaller/loader/pyiboot01_bootstrap.py", line 151, in __init__
__main__.PyInstallerImportError: ("Failed to load dynlib/dll 'OpenGL'. Most probably this dynlib/dll was not found when the application was frozen.", 'OpenGL', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pupil_invisible_monitor-script.py", line 1, in <module>
  File "/Users/pupil-labs/.pyenv/versions/3.7.4/envs/pi_monitor/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "pupil_invisible_monitor/__main__.py", line 12, in <module>
  File "/Users/pupil-labs/.pyenv/versions/3.7.4/envs/pi_monitor/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "pupil_invisible_monitor/overlay.py", line 3, in <module>
  File "/Users/pupil-labs/.pyenv/versions/3.7.4/envs/pi_monitor/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "pupil_invisible_monitor/gl_utils.py", line 15, in <module>
  File "/Users/pupil-labs/.pyenv/versions/3.7.4/envs/pi_monitor/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "OpenGL/GL/__init__.py", line 3, in <module>
  File "/Users/pupil-labs/.pyenv/versions/3.7.4/envs/pi_monitor/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "OpenGL/error.py", line 12, in <module>
  File "/Users/pupil-labs/.pyenv/versions/3.7.4/envs/pi_monitor/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "OpenGL/platform/__init__.py", line 35, in <module>
  File "OpenGL/platform/__init__.py", line 32, in _load
  File "OpenGL/platform/baseplatform.py", line 92, in install
  File "OpenGL/platform/baseplatform.py", line 14, in __get__
  File "OpenGL/platform/darwin.py", line 62, in GetCurrentContext
  File "OpenGL/platform/baseplatform.py", line 14, in __get__
  File "OpenGL/platform/darwin.py", line 45, in CGL
  File "OpenGL/platform/baseplatform.py", line 14, in __get__
  File "OpenGL/platform/darwin.py", line 41, in GL
ImportError: ('Unable to load OpenGL library', "Failed to load dynlib/dll 'OpenGL'. Most probably this dynlib/dll was not found when the application was frozen.", 'OpenGL', None)
[4169] Failed to execute script pupil_invisible_monitor-script

**Comment by papr** [comment] 2021-06-25 10:56
Ok, thanks again for testing. We would have to make changes to the bundled application. Could you try run the application from source instead?

**Comment by bhouDTU** [comment] 2021-06-26 14:27
Hi @papr , I tried but encountered some errors. I think I crashed at installing pyglui. 

(PINetwork1) baoho@Jamess-MacBook-Pro pupil-invisible-monitor % pip install .
Processing /Users/baoho/pupil-invisible-monitor
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting pyglui@ git+https://github.com/pupil-labs/pyglui.git@v1.28
  Cloning https://github.com/pupil-labs/pyglui.git (to revision v1.28) to /private/var/folders/58/3md6n35s2bq4l_m58nrl_5p00000gn/T/pip-install-rhl1x6jc/pyglui_6ea6df6bbb1d43d488988aae48eab77d
  Running command git clone -q https://github.com/pupil-labs/pyglui.git /private/var/folders/58/3md6n35s2bq4l_m58nrl_5p00000gn/T/pip-install-rhl1x6jc/pyglui_6ea6df6bbb1d43d488988aae48eab77d
  Running command git checkout -q 99eecb3732ab7574a220b53266788a7912c48efc
  Running command git submodule update --init --recursive -q
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/baoho/anaconda3/envs/PINetwork1/bin/python /Users/baoho/anaconda3/envs/PINetwork1/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/58/3md6n35s2bq4l_m58nrl_5p00000gn/T/tmp34xzrptl
       cwd: /private/var/folders/58/3md6n35s2bq4l_m58nrl_5p00000gn/T/pip-install-rhl1x6jc/pyglui_6ea6df6bbb1d43d488988aae48eab77d
  Complete output (16 lines):
  Traceback (most recent call last):
    File "/Users/baoho/anaconda3/envs/PINetwork1/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 280, in <module>
      main()
    File "/Users/baoho/anaconda3/envs/PINetwork1/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/baoho/anaconda3/envs/PINetwork1/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/private/var/folders/58/3md6n35s2bq4l_m58nrl_5p00000gn/T/pip-build-env-v7sm5pxb/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 154, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/private/var/folders/58/3md6n35s2bq4l_m58nrl_5p00000gn/T/pip-build-env-v7sm5pxb/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 135, in _get_build_requires
      self.run_setup()
    File "/private/var/folders/58/3md6n35s2bq4l_m58nrl_5p00000gn/T/pip-build-env-v7sm5pxb/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 92, in <module>
      print("generating glew.pxd based on '%s'" % glew_header)
  NameError: name 'glew_header' is not defined
  ----------------------------------------
WARNING: Discarding git+https://github.com/pupil-labs/pyglui.git@v1.28. Command errored out with exit status 1: /Users/baoho/anaconda3/envs/PINetwork1/bin/python /Users/baoho/anaconda3/envs/PINetwork1/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/58/3md6n35s2bq4l_m58nrl_5p00000gn/T/tmp34xzrptl Check the logs for full command output.
Requirement already satisfied: ndsi in /Users/baoho/anaconda3/envs/PINetwork1/lib/python3.9/site-packages (from pupil-invisible-monitor==1.3.21) (1.4.2)
ERROR: Could not find a version that satisfies the requirement pyglui (unavailable) (from pupil-invisible-monitor) (from versions: none)
ERROR: No matching distribution found for pyglui (unavailable)

**Comment by bhouDTU** [comment] 2021-06-26 14:30
Then I tried to just install pyglui, it is the same error messages about 'glew_header':

`(PINetwork1) baoho@jamess-mbp pupil-invisible-monitor % python -m pip install git+https://github.com/pupil-labs/pyglui
Collecting git+https://github.com/pupil-labs/pyglui
  Cloning https://github.com/pupil-labs/pyglui to /private/var/folders/58/3md6n35s2bq4l_m58nrl_5p00000gn/T/pip-req-build-1v17abq2
  Running command git clone -q https://github.com/pupil-labs/pyglui /private/var/folders/58/3md6n35s2bq4l_m58nrl_5p00000gn/T/pip-req-build-1v17abq2
  Running command git submodule update --init --recursive -q
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/baoho/anaconda3/envs/PINetwork1/bin/python /Users/baoho/anaconda3/envs/PINetwork1/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/58/3md6n35s2bq4l_m58nrl_5p00000gn/T/tmp78bqv2xt
       cwd: /private/var/folders/58/3md6n35s2bq4l_m58nrl_5p00000gn/T/pip-req-build-1v17abq2
  Complete output (16 lines):
  Traceback (most recent call last):
    File "/Users/baoho/anaconda3/envs/PINetwork1/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 280, in <module>
      main()
    File "/Users/baoho/anaconda3/envs/PINetwork1/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/baoho/anaconda3/envs/PINetwork1/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/private/var/folders/58/3md6n35s2bq4l_m58nrl_5p00000gn/T/pip-build-env-zwqi1_ch/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 154, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/private/var/folders/58/3md6n35s2bq4l_m58nrl_5p00000gn/T/pip-build-env-zwqi1_ch/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 135, in _get_build_requires
      self.run_setup()
    File "/private/var/folders/58/3md6n35s2bq4l_m58nrl_5p00000gn/T/pip-build-env-zwqi1_ch/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 98, in <module>
      print("generating glew.pxd based on '%s'" % glew_header)
  NameError: name 'glew_header' is not defined
  ----------------------------------------
WARNING: Discarding git+https://github.com/pupil-labs/pyglui. Command errored out with exit status 1: /Users/baoho/anaconda3/envs/PINetwork1/bin/python /Users/baoho/anaconda3/envs/PINetwork1/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/58/3md6n35s2bq4l_m58nrl_5p00000gn/T/tmp78bqv2xt Check the logs for full command output.
ERROR: Command errored out with exit status 1: /Users/baoho/anaconda3/envs/PINetwork1/bin/python /Users/baoho/anaconda3/envs/PINetwork1/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/58/3md6n35s2bq4l_m58nrl_5p00000gn/T/tmp78bqv2xt Check the logs for full command output.
`

**Comment by papr** [comment] 2021-12-06 10:42
The pyglui install issue should be fixed in the latest pyglui release.

A fixed bundle for macOS 11 Big Sur and macOS 12 Monterey has been uploaded to the release page.

**Closed by papr** 2021-12-06 10:42 UTC
